const AWS_S3_BUCKET = process.env.AWS_S3_BUCKET;
const EXTERNAL_HR_API_URL = process.env.EXTERNAL_HR_API_URL;
const EXTERNAL_HR_API_TOKEN = process.env.EXTERNAL_HR_API_TOKEN;
const MAX_SYNC_ATTEMPTS = 3;
const INITIAL_BACKOFF_DELAY = 1000; // 1 second

export { AWS_S3_BUCKET, EXTERNAL_HR_API_URL, EXTERNAL_HR_API_TOKEN, MAX_SYNC_ATTEMPTS, INITIAL_BACKOFF_DELAY };
