import { pgTable, varchar, boolean, index, numeric, timestamp, integer, text } from 'drizzle-orm/pg-core';

export const sal_structure = pgTable(
  'sal_structure',
  {
    pk_ss_id: numeric("pk_ss_id", { precision: 18, scale: 0 }).primaryKey().notNull(),
    fk_emp_id: numeric("fk_emp_id", { precision: 18, scale: 0 }).notNull(),
    sal_start: timestamp("sal_start", { mode: "string" }).notNull(),
    basic: numeric("basic", { precision: 19, scale: 4 }).notNull().default("0"),
    b_type: varchar("b_type", { length: 7 }).notNull().default(""),
    allowance: numeric("allowance", { precision: 19, scale: 4 }),
    t_allowance: varchar("t_allowance", { length: 5 }).notNull().default(""),
    travelling: numeric("travelling", { precision: 19, scale: 4 }),
    t_travelling: varchar("t_travelling", { length: 5 }).notNull().default(""),
    housing: numeric("housing", { precision: 19, scale: 4 }),
    t_housing: varchar("t_housing", { length: 5 }).notNull().default(""),
    daily: numeric("daily", { precision: 19, scale: 4 }),
    t_daily: varchar("t_daily", { length: 5 }).notNull().default(""),
    incentive: numeric("incentive", { precision: 19, scale: 4 }),
    t_incentive: varchar("t_incentive", { length: 5 }).notNull().default(""),
    education: numeric("education", { precision: 19, scale: 4 }),
    t_education: varchar("t_education", { length: 5 }).notNull().default(""),
    medical: numeric("medical", { precision: 19, scale: 4 }),
    t_medical: varchar("t_medical", { length: 5 }).notNull().default(""),
    other: numeric("other", { precision: 19, scale: 4 }),
    t_other: varchar("t_other", { length: 5 }).notNull().default(""),
    oti: numeric("oti", { precision: 19, scale: 4 }),
    t_oti: boolean("t_oti").notNull().default(false),
    otii: numeric("otii", { precision: 19, scale: 4 }),
    t_otii: boolean("t_otii").notNull().default(false),
    r_day_i: varchar("r_day_i", { length: 10 }).notNull().default(""),
    r_day_ii: varchar("r_day_ii", { length: 10 }).notNull().default(""),
    ph: integer("ph").notNull().default(0),
    sl: numeric("sl", { precision: 10, scale: 1 }).notNull().default("0"),
    cl: numeric("cl", { precision: 10, scale: 1 }).notNull().default("0"),
    ucl: numeric("ucl", { precision: 10, scale: 1 }).notNull().default("0"),
    wh: numeric("wh", { precision: 18, scale: 2 }).notNull().default("0"),
    rwh: numeric("rwh", { precision: 18, scale: 2 }).notNull().default("0"),
    bl: integer("bl").notNull().default(0),
    bld: integer("bld").notNull().default(0),
    a_rule: varchar("a_rule", { length: 10 }).notNull().default(""),
    otb: numeric("otb", { precision: 18, scale: 0 }).notNull().default("0"),
    cal_pt: boolean("cal_pt").notNull().default(false),
    cal_pf: boolean("cal_pf").notNull().default(false),
    cal_esic: boolean("cal_esic").notNull().default(false),
    cal_tds: boolean("cal_tds").notNull().default(false),
    slab_tds: integer("slab_tds"),
    revise: timestamp("revise", { mode: "string" }).notNull(),
    scan_mb: boolean("scan_mb"),
    fk_s_acct_id: varchar("fk_s_acct_id", { length: 10 }).notNull().default(""),
    remarks: varchar("remarks", { length: 100 }).notNull().default(""),
    sync: varchar("sync", { length: 1 }).notNull().default("N"),
    sys_defined: boolean("sys_defined").notNull().default(false),
    date_timestamp: timestamp("date_timestamp", { mode: "string" }).notNull().defaultNow(),
    fk_user_id: varchar("fk_user_id", { length: 5 }).notNull().default(""),
    last_status: varchar("last_status", { length: 10 }).notNull().default(""),
    other_basic: boolean("other_basic").notNull().default(false),
    eot: boolean("eot").notNull().default(false),
    e_whour: boolean("e_whour").notNull().default(false),
    lye_whour: numeric("lye_whour", { precision: 19, scale: 2 }).notNull().default("0"),
    fk_l_acct_id: varchar("fk_l_acct_id", { length: 10 }).notNull().default(""),
    ma_basic: boolean("ma_basic").notNull().default(false),
    ea_basic: boolean("ea_basic").notNull().default(false),
    incentive_basic: boolean("incentive_basic").notNull().default(false),
    da_basic: boolean("da_basic").notNull().default(false),
    ha_basic: boolean("ha_basic").notNull().default(false),
    ta_basic: boolean("ta_basic").notNull().default(false),
    allowance_basic: boolean("allowance_basic").notNull().default(false),
    fk_f_cont_id: varchar("fk_f_cont_id", { length: 10 }),
    fk_t_cont_id: varchar("fk_t_cont_id", { length: 10 }),
    sal_gross: numeric("sal_gross", { precision: 19, scale: 4 }).notNull().default("0"),
    fk_i_acct_id: varchar("fk_i_acct_id", { length: 10 }),
    ab_penalty: numeric("ab_penalty", { precision: 19, scale: 4 }).notNull().default("0"),
    variant: boolean("variant").notNull().default(false),
    pfa: boolean("pfa").notNull().default(false),
    pfta: boolean("pfta").notNull().default(false),
    pfha: boolean("pfha").notNull().default(false),
    pfi: boolean("pfi").notNull().default(false),
    pfea: boolean("pfea").notNull().default(false),
    pfma: boolean("pfma").notNull().default(false),
    pfoa: boolean("pfoa").notNull().default(false),
    rd_variant: boolean("rd_variant").notNull().default(false),
    retention: numeric("retention", { precision: 19, scale: 4 }),
    fk_emp1_id: numeric("fk_emp1_id", { precision: 18, scale: 0 }),
    fk_emp2_id: numeric("fk_emp2_id", { precision: 18, scale: 0 }),
    fk_r_acct_id: varchar("fk_r_acct_id", { length: 10 }),
    sal_daily: numeric("sal_daily", { precision: 19, scale: 4 }),
    set_pf: boolean("set_pf").notNull().default(false),
    sandwich: boolean("sandwich").notNull().default(false),
    gha: boolean("gha").notNull().default(false),
    rda: boolean("rda").notNull().default(false),
    iorf: boolean("iorf").notNull().default(false),
    oaop: boolean("oaop").notNull().default(false),
    l_time_r_off: integer("l_time_r_off"),
    latitude: numeric("latitude", { precision: 18, scale: 6 }),
    longitude: numeric("longitude", { precision: 18, scale: 6 }),
    tds_deduct: numeric("tds_deduct", { precision: 18, scale: 0 }).notNull().default("0"),
    m_deduction: numeric("m_deduction", { precision: 18, scale: 2 }),
    ded_description: varchar("ded_description", { length: 100 }),
    fk_des_id: varchar("fk_des_id", { length: 5 }),
  },
  (t) => [
    index('idx_sal_structure_emp').on(t.fk_emp_id),
    index('idx_sal_structure_dates').on(t.sal_start, t.revise),
  ],
);
