// shared/database/init.ts
import '../../load-env.js';

import { sql } from 'drizzle-orm';

import { commonDb } from '@/config/db.config.js';
import { logger } from '@/shared/utils/devHelper.js';

export async function initializeCommonDb(): Promise<void> {
  try {
    logger.info('Initializing common database (tionix_one)...');

    // Create the account_book table inside AAAcommon if it does not exist
    await commonDb.execute(sql`
      CREATE TABLE IF NOT EXISTS "account_book" (
        "pk_book_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "book_name" varchar(50) NOT NULL,
        "active" boolean NOT NULL,
        "file_name" varchar(255) NOT NULL,
        "database_name" varchar(50) NOT NULL,
        "product_id" numeric(18,0) NOT NULL,
        "parent_id" numeric(18,0) NOT NULL,
        "add_path" varchar(12) NOT NULL,
        "backup_path" varchar(255) NOT NULL
      );
    `);

    // Create the active_server table inside AAAcommon if it does not exist
    await commonDb.execute(sql`
      CREATE TABLE IF NOT EXISTS "active_server" (
        "active_server" varchar(50) NOT NULL,
        "product_id" integer NOT NULL,
        "parent_id" integer NOT NULL,
        "user_id" varchar(50) NOT NULL,
        "password" varchar(255) NOT NULL,
        "fk_book_id" char(23)
      );
    `);

    logger.info('Common database initialized successfully.');
  } catch (error: any) {
    logger.error('Failed to initialize common database:', error);
  }
}

// Support executing directly via CLI
if (
  import.meta.url === `file://${process.argv[1]}` ||
  (process.argv[1] && (process.argv[1].endsWith('init.ts') || process.argv[1].endsWith('init.js')))
) {
  initializeCommonDb()
    .then(() => {
      process.exit(0);
    })
    .catch((err) => {
      logger.error('CLI execution failed:', err);
      process.exit(1);
    });
}
