// ─── sal-nature-of-work.controller.ts ───────────────────────────────────────
import type { Request, Response } from 'express';
import asyncHandler from 'express-async-handler';

import {
  createNatureOfWorkSchema,
  updateNatureOfWorkSchema,
  deleteNatureOfWorkSchema,
  listNatureOfWorkSchema,
} from './sal-nature-of-work.dto.js';
import {
  listNatureOfWork,
  getNatureOfWorkById,
  createNatureOfWork,
  updateNatureOfWork,
  deleteNatureOfWork,
} from './sal-nature-of-work.service.js';

const NATURE_OF_WORK_MODULE_NAME = 'master-salary/Nature of Work';

// GET /nature-of-work
export const list = asyncHandler(async (req: Request, res: Response): Promise<void> => {
  const parsed = listNatureOfWorkSchema.parse(req.query);
  const result = await listNatureOfWork(parsed);
  if (!result.success) {
    res.build
      .withStatus(500)
      .withError('INTERNAL_ERROR', result.message)
      .withMessage('Internal Server Error')
      .fail()
      .send();
    return;
  }
  res.build
    .withStatus(200)
    .withModule(NATURE_OF_WORK_MODULE_NAME)
    .withMessage('Nature of Work list retrieved successfully')
    .withData(result.data)
    .success()
    .send();
});

// GET /nature-of-work/:id
export const getById = asyncHandler(async (req: Request, res: Response): Promise<void> => {
  const id = parseInt(req.params.id as string, 10);
  if (isNaN(id)) {
    res.build
      .withStatus(400)
      .withError('INVALID_ID', 'ID must be a number.')
      .withMessage('Bad Request - Invalid ID')
      .fail()
      .send();
    return;
  }
  const result = await getNatureOfWorkById(id);
  if (!result.success) {
    res.build
      .withStatus(500)
      .withError('INTERNAL_ERROR', result.message)
      .withMessage('Internal Server Error')
      .fail()
      .send();
    return;
  }
  if (result.data === null) {
    res.build
      .withStatus(404)
      .withError('NOT_FOUND', 'Record not found.')
      .withMessage('Record not found')
      .fail()
      .send();
    return;
  }
  res.build
    .withStatus(200)
    .withModule(NATURE_OF_WORK_MODULE_NAME)
    .withMessage('Nature of Work record retrieved successfully')
    .withData(result.data)
    .success()
    .send();
});

// POST /nature-of-work
export const create = asyncHandler(async (req: Request, res: Response): Promise<void> => {
  const parsed = createNatureOfWorkSchema.parse(req.body);
  const result = await createNatureOfWork(parsed);
  if (!result.success) {
    res.build
      .withStatus(409)
      .withError('CONFLICT', result.message)
      .withMessage('Conflict - Resource already exists')
      .fail()
      .send();
    return;
  }
  res.build
    .withStatus(201)
    .withModule(NATURE_OF_WORK_MODULE_NAME)
    .withMessage('Nature of Work created successfully')
    .withData(result.data)
    .success()
    .send();
});

// PUT /nature-of-work/:id
export const update = asyncHandler(async (req: Request, res: Response): Promise<void> => {
  const id = parseInt(req.params.id as string, 10);
  if (isNaN(id)) {
    res.build
      .withStatus(400)
      .withError('INVALID_ID', 'ID must be a number.')
      .withMessage('Bad Request - Invalid ID')
      .fail()
      .send();
    return;
  }
  const parsed = updateNatureOfWorkSchema.parse({
    ...req.body,
    pk_nw_id: id,
  });
  const result = await updateNatureOfWork(parsed);
  if (!result.success) {
    const status = result.message === 'Record not found.' ? 404 : 409;
    const msg = status === 404 ? 'Record not found' : 'Conflict - Resource already exists';
    res.build
      .withStatus(status)
      .withError('UPDATE_ERROR', result.message)
      .withMessage(msg)
      .fail()
      .send();
    return;
  }
  res.build
    .withStatus(200)
    .withModule(NATURE_OF_WORK_MODULE_NAME)
    .withMessage('Nature of Work updated successfully')
    .withData(result.data)
    .success()
    .send();
});

// DELETE /nature-of-work/:id
export const remove = asyncHandler(async (req: Request, res: Response): Promise<void> => {
  const id = parseInt(req.params.id as string, 10);
  if (isNaN(id)) {
    res.build
      .withStatus(400)
      .withError('INVALID_ID', 'ID must be a number.')
      .withMessage('Bad Request - Invalid ID')
      .fail()
      .send();
    return;
  }
  const parsed = deleteNatureOfWorkSchema.parse({ pk_nw_id: id });
  const result = await deleteNatureOfWork(parsed);
  if (!result.success) {
    const status =
      result.message?.includes('related to other data') ||
      result.message?.includes('generated by application')
        ? 409
        : result.message === 'Record not found.'
          ? 404
          : 500;
    const msg =
      status === 404
        ? 'Record not found'
        : status === 409
          ? 'Conflict - Deletion constraint check failed'
          : 'Internal Server Error';
    res.build
      .withStatus(status)
      .withError('DELETE_ERROR', result.message)
      .withMessage(msg)
      .fail()
      .send();
    return;
  }
  res.build
    .withStatus(200)
    .withModule(NATURE_OF_WORK_MODULE_NAME)
    .withMessage('Nature of Work deleted successfully')
    .withData(result.data)
    .success()
    .send();
});
