CREATE TABLE "app_user" (
	"pk_user_id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "app_user_pk_user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_name" varchar(15) NOT NULL,
	"password" varchar(10),
	"answer" varchar(50),
	"sync" varchar(1),
	"sys_defined" boolean,
	"datetime_stamp" timestamp DEFAULT now(),
	"fk_user_id" bigint,
	"last_status" varchar(10),
	"fk_ec_id" numeric(18, 0),
	"own_records" boolean,
	"other_records" boolean,
	"mobile" varchar(20),
	"fk_emp_id" numeric(18, 0)
);
--> statement-breakpoint
CREATE TABLE "new_id" (
	"form_name" varchar(100) PRIMARY KEY NOT NULL,
	"prefix" varchar(5),
	"last_id" numeric(18, 0),
	"start_with" numeric(18, 0),
	"len" numeric(18, 0),
	"module_name" varchar(50),
	"module_caption" varchar(50),
	"module_id" numeric(18, 0),
	"form_id" numeric(18, 0),
	"news" boolean
);
--> statement-breakpoint
CREATE TABLE "app_user_right" (
	"pk_right_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_user_right_pk_right_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"form" varchar(100) NOT NULL,
	"user_id" bigint NOT NULL,
	"add" boolean,
	"edit" boolean,
	"delete" boolean,
	"view" boolean,
	"print" boolean,
	"export" boolean,
	"authorize" boolean,
	"sync" varchar(1) DEFAULT 'N' NOT NULL,
	"sys_defined" boolean DEFAULT false NOT NULL,
	"date_timestamp" timestamp DEFAULT now() NOT NULL,
	"fk_user_id" bigint NOT NULL,
	"last_status" varchar(10) DEFAULT '' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_user_report" (
	"pk_rpt_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_user_report_pk_rpt_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"form" varchar(100) NOT NULL,
	"user_id" bigint NOT NULL,
	"view" boolean,
	"print" boolean,
	"export" boolean,
	"sync" varchar(1) DEFAULT 'N' NOT NULL,
	"sys_defined" boolean DEFAULT false NOT NULL,
	"date_timestamp" timestamp DEFAULT now() NOT NULL,
	"fk_user_id" bigint NOT NULL,
	"last_status" varchar(10) DEFAULT '' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_user_other" (
	"pk_oth_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_user_other_pk_oth_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"form" varchar(100) NOT NULL,
	"user_id" bigint NOT NULL,
	"rights" boolean,
	"sync" varchar(1) DEFAULT 'N' NOT NULL,
	"sys_defined" boolean DEFAULT false NOT NULL,
	"date_timestamp" timestamp DEFAULT now() NOT NULL,
	"fk_user_id" bigint NOT NULL,
	"last_status" varchar(10) DEFAULT '' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_user_special" (
	"pk_spe_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_user_special_pk_spe_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"form" varchar(75) NOT NULL,
	"user_id" bigint NOT NULL,
	"rights" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_user_branch" (
	"pk_br_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_user_branch_pk_br_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"fk_user_id" bigint NOT NULL,
	"fk_set_id" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_user_dashboard" (
	"pk_db_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_user_dashboard_pk_db_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"fk_user_id" bigint NOT NULL,
	"id" numeric(18, 0) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_user_process" (
	"pk_pr_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_user_process_pk_pr_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"fk_prod_id" varchar(10) NOT NULL,
	"fk_user_id" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "attendance_locations" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "attendance_locations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"location_name" varchar(100) NOT NULL,
	"latitude" numeric(10, 7) NOT NULL,
	"longitude" numeric(10, 7) NOT NULL,
	"address" text,
	"allowed_radius" numeric(10, 2) DEFAULT '100.00',
	"location_type" varchar(50),
	"is_active" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "attendance" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "attendance_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"pay_code" varchar(50),
	"emp_code" varchar(50) NOT NULL,
	"emp_name" varchar(100),
	"at_date" varchar(20) NOT NULL,
	"punch_time" varchar(20),
	"punch_datetime" timestamp DEFAULT now() NOT NULL,
	"device" varchar(50) DEFAULT 'ReactNative',
	"punch" varchar(20),
	"manual" varchar(1) DEFAULT 'N',
	"status" integer DEFAULT 1,
	"latitude" numeric(10, 7),
	"longitude" numeric(10, 7),
	"address" text
);
--> statement-breakpoint
CREATE TABLE "gps_attendance_logs" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "gps_attendance_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"employee_id" varchar(50) NOT NULL,
	"attendance_type" varchar(20) NOT NULL,
	"attendance_date" varchar(20) NOT NULL,
	"recorded_at" timestamp DEFAULT now() NOT NULL,
	"employee_latitude" numeric(10, 7) NOT NULL,
	"employee_longitude" numeric(10, 7) NOT NULL,
	"employee_address" text,
	"office_latitude" numeric(10, 7) NOT NULL,
	"office_longitude" numeric(10, 7) NOT NULL,
	"distance_meters" numeric(10, 2) NOT NULL,
	"allowed_radius_meters" numeric(10, 2) NOT NULL,
	"attendance_status" varchar(20) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "admin_sessions" (
	"session_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "admin_sessions_session_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"admin_user_id" integer NOT NULL,
	"refresh_token" varchar(500) NOT NULL,
	"device_info" varchar(500),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"expires_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user_sessions" (
	"session_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_sessions_session_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"refresh_token" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"expires_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "account_book" (
	"pk_book_id" char(23) PRIMARY KEY NOT NULL,
	"book_name" varchar(50) NOT NULL,
	"active" boolean NOT NULL,
	"file_name" varchar(255) NOT NULL,
	"database_name" varchar(50) NOT NULL,
	"product_id" numeric(18, 0) NOT NULL,
	"parent_id" numeric(18, 0) NOT NULL,
	"add_path" varchar(12) NOT NULL,
	"backup_path" varchar(255) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "active_server" (
	"active_server" varchar(50) NOT NULL,
	"product_id" integer NOT NULL,
	"parent_id" integer NOT NULL,
	"user_id" varchar(50) NOT NULL,
	"password" varchar(255) NOT NULL,
	"fk_book_id" char(23)
);
--> statement-breakpoint
CREATE TABLE "acct_group" (
	"pk_grp_id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "acct_group_pk_grp_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"group_name" varchar(40) NOT NULL,
	"fk_main_id" integer NOT NULL,
	"fk_sub_id" integer NOT NULL,
	"fk_prt_id" integer NOT NULL,
	"grouping" integer NOT NULL,
	"prefix" varchar(1) NOT NULL,
	"dc" varchar(2) NOT NULL,
	"sync" char(1) DEFAULT 'N' NOT NULL,
	"sys_defined" boolean DEFAULT false NOT NULL,
	"date_time_stamp" timestamp NOT NULL,
	"fk_user_id" bigint NOT NULL,
	"last_status" varchar(10) NOT NULL,
	CONSTRAINT "acct_group_group_name_unique" UNIQUE("group_name")
);
--> statement-breakpoint
CREATE TABLE "sal_employee" (
	"pk_emp_id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "sal_employee_pk_emp_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"emp_code" varchar(30) NOT NULL,
	"fk_tit_id" char(5),
	"employee" varchar(50) NOT NULL,
	"doj" timestamp NOT NULL,
	"dob" timestamp,
	"photo" varchar(255),
	"fk_qual_id" char(5),
	"gender" varchar(10) NOT NULL,
	"martial_status" varchar(15) NOT NULL,
	"anni" timestamp,
	"p_address" varchar(255) NOT NULL,
	"n_address" varchar(255) NOT NULL,
	"fk_dep_id" char(5),
	"fk_deg_id" char(5),
	"fk_bnk_id" char(10),
	"account_no" varchar(20) NOT NULL,
	"pf_no" varchar(25) NOT NULL,
	"esic_no" varchar(25) NOT NULL,
	"pan_no" varchar(25) NOT NULL,
	"dol" timestamp,
	"blood_grp" varchar(6) NOT NULL,
	"wp" varchar(50) NOT NULL,
	"aadhar" varchar(50) NOT NULL,
	"cv_copy" varchar(50) NOT NULL,
	"le_copy" varchar(50) NOT NULL,
	"fk_m_doc_id" numeric(18, 0),
	"username" varchar(15) NOT NULL,
	"password" varchar(255) NOT NULL,
	"question" varchar(50) NOT NULL,
	"answer" varchar(50) NOT NULL,
	"ext" varchar(10) NOT NULL,
	"sync" char(1) NOT NULL,
	"sys_defined" boolean NOT NULL,
	"date_timestamp" timestamp NOT NULL,
	"fk_user_id" char(5) NOT NULL,
	"last_status" varchar(10) NOT NULL,
	"rtgs" varchar(20) NOT NULL,
	"s_address" varchar(30) NOT NULL,
	"sb" boolean NOT NULL,
	"fk_set_id" char(5),
	"type" varchar(20) NOT NULL,
	"att_type" boolean NOT NULL,
	"height" numeric(18, 0),
	"weight" numeric(18, 2),
	"fk_rg_id" numeric(18, 0),
	"fk_cs_id" numeric(18, 0),
	"fk_st_id" numeric(18, 0),
	"mark" varchar(50) NOT NULL,
	"experience" varchar(5),
	"fk_r_emp_id" numeric(18, 0),
	"police" varchar(50) NOT NULL,
	"add_police" varchar(255) NOT NULL,
	"cont_police" varchar(25) NOT NULL,
	"fk_w1_emp_id" numeric(18, 0),
	"fk_w2_emp_id" numeric(18, 0),
	"personality1" varchar(50) NOT NULL,
	"fk_p1_des_id" char(5),
	"p1_address" varchar(255) NOT NULL,
	"p1_contact" varchar(25) NOT NULL,
	"personality2" varchar(50) NOT NULL,
	"fk_p2_des_id" char(5),
	"p2_address" varchar(255) NOT NULL,
	"p2_contact" varchar(25) NOT NULL,
	"messaging" boolean NOT NULL,
	"fk_acct_id" char(10),
	"geolocation" boolean NOT NULL,
	"employment" varchar(3) NOT NULL,
	"inform_pf" boolean,
	"inform_esic" boolean
);
--> statement-breakpoint
CREATE TABLE "app_questions" (
	"pk_question_id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "app_questions_pk_question_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"questions" varchar(255) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "email_configuration" (
	"pk_ec_id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "email_configuration_pk_ec_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"from_email" varchar(75) NOT NULL,
	"password" varchar(30) NOT NULL,
	"pop_server" varchar(30) NOT NULL,
	"pop_port" integer NOT NULL,
	"smtp_server" varchar(30) NOT NULL,
	"smtp_port" integer NOT NULL,
	"to_email" varchar(75) NOT NULL,
	"ssl" boolean NOT NULL,
	"sync" char(1) NOT NULL,
	"sys_defined" boolean NOT NULL,
	"date_timestamp" timestamp NOT NULL,
	"fk_user_id" char(5) NOT NULL,
	"last_status" varchar(10) NOT NULL,
	"m_default" boolean NOT NULL
);
--> statement-breakpoint
ALTER TABLE "app_user_right" ADD CONSTRAINT "app_user_right_form_new_id_form_name_fk" FOREIGN KEY ("form") REFERENCES "public"."new_id"("form_name") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_user_right" ADD CONSTRAINT "app_user_right_user_id_app_user_pk_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."app_user"("pk_user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_user_right" ADD CONSTRAINT "app_user_right_fk_user_id_app_user_pk_user_id_fk" FOREIGN KEY ("fk_user_id") REFERENCES "public"."app_user"("pk_user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_user_report" ADD CONSTRAINT "app_user_report_form_new_id_form_name_fk" FOREIGN KEY ("form") REFERENCES "public"."new_id"("form_name") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_user_report" ADD CONSTRAINT "app_user_report_user_id_app_user_pk_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."app_user"("pk_user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_user_report" ADD CONSTRAINT "app_user_report_fk_user_id_app_user_pk_user_id_fk" FOREIGN KEY ("fk_user_id") REFERENCES "public"."app_user"("pk_user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_user_other" ADD CONSTRAINT "app_user_other_form_new_id_form_name_fk" FOREIGN KEY ("form") REFERENCES "public"."new_id"("form_name") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_user_other" ADD CONSTRAINT "app_user_other_user_id_app_user_pk_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."app_user"("pk_user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_user_other" ADD CONSTRAINT "app_user_other_fk_user_id_app_user_pk_user_id_fk" FOREIGN KEY ("fk_user_id") REFERENCES "public"."app_user"("pk_user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_user_special" ADD CONSTRAINT "app_user_special_user_id_app_user_pk_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."app_user"("pk_user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_user_branch" ADD CONSTRAINT "app_user_branch_fk_user_id_app_user_pk_user_id_fk" FOREIGN KEY ("fk_user_id") REFERENCES "public"."app_user"("pk_user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_user_dashboard" ADD CONSTRAINT "app_user_dashboard_fk_user_id_app_user_pk_user_id_fk" FOREIGN KEY ("fk_user_id") REFERENCES "public"."app_user"("pk_user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_user_process" ADD CONSTRAINT "app_user_process_fk_user_id_app_user_pk_user_id_fk" FOREIGN KEY ("fk_user_id") REFERENCES "public"."app_user"("pk_user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "admin_sessions" ADD CONSTRAINT "admin_sessions_admin_user_id_app_user_pk_user_id_fk" FOREIGN KEY ("admin_user_id") REFERENCES "public"."app_user"("pk_user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_sessions" ADD CONSTRAINT "user_sessions_user_id_app_user_pk_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."app_user"("pk_user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "active_server" ADD CONSTRAINT "active_server_fk_book_id_account_book_pk_book_id_fk" FOREIGN KEY ("fk_book_id") REFERENCES "public"."account_book"("pk_book_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "acct_group" ADD CONSTRAINT "acct_group_fk_main_id_acct_group_pk_grp_id_fk" FOREIGN KEY ("fk_main_id") REFERENCES "public"."acct_group"("pk_grp_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "acct_group" ADD CONSTRAINT "acct_group_fk_sub_id_acct_group_pk_grp_id_fk" FOREIGN KEY ("fk_sub_id") REFERENCES "public"."acct_group"("pk_grp_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "acct_group" ADD CONSTRAINT "acct_group_fk_prt_id_acct_group_pk_grp_id_fk" FOREIGN KEY ("fk_prt_id") REFERENCES "public"."acct_group"("pk_grp_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "acct_group" ADD CONSTRAINT "acct_group_fk_user_id_app_user_pk_user_id_fk" FOREIGN KEY ("fk_user_id") REFERENCES "public"."app_user"("pk_user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "uq_app_user_right" ON "app_user_right" USING btree ("user_id","form");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_app_user_report" ON "app_user_report" USING btree ("user_id","form");