CREATE TABLE "cont_country" (
	"pk_ctry_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cont_country_pk_ctry_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"country" varchar(50) NOT NULL,
	"isd_code" varchar(20) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cont_state" (
	"pk_state_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cont_state_pk_state_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"state" varchar(30) NOT NULL,
	"fk_ctry_id" integer NOT NULL,
	"state_code" varchar(10) DEFAULT '' NOT NULL,
	"sync" char(1) DEFAULT 'N' NOT NULL,
	"sys_defined" boolean DEFAULT false NOT NULL,
	"date_time_stamp" timestamp DEFAULT now() NOT NULL,
	"fk_user_id" integer NOT NULL,
	"last_status" varchar(10) DEFAULT '' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cont_city" (
	"pk_city_id" char(7) PRIMARY KEY NOT NULL,
	"city" varchar(30) NOT NULL,
	"fk_state_id" integer,
	"fk_ctry_id" integer NOT NULL,
	"std_code" varchar(10) DEFAULT '' NOT NULL,
	"sync" char(1) DEFAULT 'N' NOT NULL,
	"sys_defined" boolean DEFAULT false NOT NULL,
	"date_time_stamp" timestamp DEFAULT now() NOT NULL,
	"fk_user_id" integer NOT NULL,
	"last_status" varchar(10) DEFAULT '' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cont_common" (
	"pk_cont_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cont_common_pk_cont_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"contact_name" varchar(50) NOT NULL,
	"address" varchar(150) DEFAULT '' NOT NULL,
	"fk_city_id" char(7),
	"region" varchar(50) DEFAULT '' NOT NULL,
	"pincode" numeric(18, 0),
	"sync" char(1) DEFAULT 'N' NOT NULL,
	"sys_defined" boolean DEFAULT false NOT NULL,
	"date_time_stamp" timestamp DEFAULT now() NOT NULL,
	"fk_user_id" integer NOT NULL,
	"last_status" varchar(10) DEFAULT '' NOT NULL,
	"postfix" varchar(25) DEFAULT '' NOT NULL,
	"fk_emp_id" numeric(18, 0),
	"fk_a_user_id" integer,
	"a_timestamp" timestamp,
	"username" varchar(40),
	"password" varchar(20),
	"question" varchar(50),
	"answer" varchar(50),
	"client_id" varchar(30) DEFAULT '' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cont_address" (
	"pk_ca_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cont_address_pk_ca_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"fk_cont_id" integer,
	"address" varchar(150) NOT NULL,
	"fk_city_id" char(7),
	"region" varchar(50) DEFAULT '' NOT NULL,
	"pincode" numeric(18, 0),
	"sync" char(1) DEFAULT 'N' NOT NULL,
	"sys_defined" boolean DEFAULT false NOT NULL,
	"date_time_stamp" timestamp DEFAULT now() NOT NULL,
	"fk_user_id" integer NOT NULL,
	"last_status" varchar(10) DEFAULT '' NOT NULL
);
--> statement-breakpoint
ALTER TABLE "cont_state" ADD CONSTRAINT "cont_state_fk_ctry_id_cont_country_pk_ctry_id_fk" FOREIGN KEY ("fk_ctry_id") REFERENCES "public"."cont_country"("pk_ctry_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cont_state" ADD CONSTRAINT "cont_state_fk_user_id_app_user_pk_user_id_fk" FOREIGN KEY ("fk_user_id") REFERENCES "public"."app_user"("pk_user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cont_city" ADD CONSTRAINT "cont_city_fk_state_id_cont_state_pk_state_id_fk" FOREIGN KEY ("fk_state_id") REFERENCES "public"."cont_state"("pk_state_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cont_city" ADD CONSTRAINT "cont_city_fk_ctry_id_cont_country_pk_ctry_id_fk" FOREIGN KEY ("fk_ctry_id") REFERENCES "public"."cont_country"("pk_ctry_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cont_city" ADD CONSTRAINT "cont_city_fk_user_id_app_user_pk_user_id_fk" FOREIGN KEY ("fk_user_id") REFERENCES "public"."app_user"("pk_user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cont_common" ADD CONSTRAINT "cont_common_fk_city_id_cont_city_pk_city_id_fk" FOREIGN KEY ("fk_city_id") REFERENCES "public"."cont_city"("pk_city_id") ON DELETE no action ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "cont_common" ADD CONSTRAINT "cont_common_fk_user_id_app_user_pk_user_id_fk" FOREIGN KEY ("fk_user_id") REFERENCES "public"."app_user"("pk_user_id") ON DELETE no action ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "cont_common" ADD CONSTRAINT "cont_common_fk_emp_id_sal_employee_pk_emp_id_fk" FOREIGN KEY ("fk_emp_id") REFERENCES "public"."sal_employee"("pk_emp_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cont_common" ADD CONSTRAINT "cont_common_fk_a_user_id_app_user_pk_user_id_fk" FOREIGN KEY ("fk_a_user_id") REFERENCES "public"."app_user"("pk_user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cont_address" ADD CONSTRAINT "cont_address_fk_cont_id_cont_common_pk_cont_id_fk" FOREIGN KEY ("fk_cont_id") REFERENCES "public"."cont_common"("pk_cont_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cont_address" ADD CONSTRAINT "cont_address_fk_city_id_cont_city_pk_city_id_fk" FOREIGN KEY ("fk_city_id") REFERENCES "public"."cont_city"("pk_city_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cont_address" ADD CONSTRAINT "cont_address_fk_user_id_app_user_pk_user_id_fk" FOREIGN KEY ("fk_user_id") REFERENCES "public"."app_user"("pk_user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "ix_cont_city_city" ON "cont_city" USING btree ("city");