CREATE TABLE "cont_moc" (
	"pk_moc_id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "cont_moc_pk_moc_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"moc" varchar(25) NOT NULL,
	"fk_mt_id" integer NOT NULL,
	"sync" char(1) NOT NULL,
	"sys_defined" boolean DEFAULT false NOT NULL,
	"date_timestamp" timestamp NOT NULL,
	"fk_user_id" integer NOT NULL,
	"last_status" varchar(10) NOT NULL,
	CONSTRAINT "ix_cont_moc" UNIQUE("moc")
);
--> statement-breakpoint
CREATE TABLE "cont_moc_type" (
	"pk_mt_id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "cont_moc_type_pk_mt_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"mode" varchar(6) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cont_region" (
	"pk_reg_id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "cont_region_pk_reg_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"region" varchar(30) NOT NULL,
	"rate1" numeric(19, 2) NOT NULL,
	"rate2" numeric(19, 2) NOT NULL,
	"sync" char(1) NOT NULL,
	"sys_defined" boolean DEFAULT false NOT NULL,
	"date_timestamp" timestamp NOT NULL,
	"fk_user_id" integer NOT NULL,
	"last_status" varchar(10) NOT NULL,
	CONSTRAINT "ix_cont_region" UNIQUE("region")
);
--> statement-breakpoint
CREATE TABLE "cont_individual" (
	"pk_ind_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cont_individual_pk_ind_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"fk_com_id" integer NOT NULL,
	"fk_tit_id" integer,
	"first_name" varchar(50) NOT NULL,
	"middle_name" varchar(40) DEFAULT '' NOT NULL,
	"surname" varchar(25) NOT NULL,
	"dob" timestamp,
	"photo_url" varchar(500),
	"fk_qual_id" integer,
	"gender" varchar(25) DEFAULT '',
	"marital_status" varchar(25) DEFAULT 'single' NOT NULL,
	"fk_org_id" integer,
	"fk_dep_id" integer,
	"fk_deg_id" integer,
	"fk_spo_id" integer,
	"anniversy" timestamp,
	"ext" varchar(10)
);
--> statement-breakpoint
CREATE TABLE "sal_annual_leave" (
	"pk_sal_id" varchar(50) PRIMARY KEY NOT NULL,
	"fk_emp_id" varchar(50) NOT NULL,
	"cal_year" integer NOT NULL,
	"al_roff" varchar(20) DEFAULT '0',
	"py_bal" varchar(20) DEFAULT '0',
	"tot_al" varchar(20) DEFAULT '0'
);
--> statement-breakpoint
CREATE TABLE "sal_leave_encashment" (
	"pk_sle_id" varchar(50) PRIMARY KEY NOT NULL,
	"fk_emp_id" varchar(50) NOT NULL,
	"le_year" integer NOT NULL,
	"e_day" varchar(20) DEFAULT '0'
);
--> statement-breakpoint
CREATE TABLE "sal_holidays" (
	"pk_sh_id" varchar(50) PRIMARY KEY NOT NULL,
	"holiday_date" date NOT NULL,
	"holiday_name" varchar(100)
);
--> statement-breakpoint
CREATE TABLE "sal_sel_holidays" (
	"pk_sel_id" varchar(50) PRIMARY KEY NOT NULL,
	"fk_ss_id" varchar(50) NOT NULL,
	"fk_sh_id" varchar(50) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sal_attendance" (
	"pk_at_id" varchar(50) PRIMARY KEY NOT NULL,
	"fk_ss_id" varchar(50) NOT NULL,
	"at_date" date NOT NULL,
	"w_type" varchar(50),
	"authorize" boolean DEFAULT false
);
--> statement-breakpoint
CREATE TABLE "sal_m_attendance" (
	"pk_at_id" varchar(50) PRIMARY KEY NOT NULL,
	"fk_ss_id" varchar(50) NOT NULL,
	"authorize" boolean DEFAULT false
);
--> statement-breakpoint
CREATE TABLE "sal_m_atten_date" (
	"pk_mad_id" varchar(50) PRIMARY KEY NOT NULL,
	"fk_at_id" varchar(50) NOT NULL,
	"a_date" date NOT NULL,
	"w_type" varchar(50)
);
--> statement-breakpoint
CREATE TABLE "sal_leave_request" (
	"pk_lr_id" varchar(50) PRIMARY KEY NOT NULL,
	"request_no" varchar(20) NOT NULL,
	"request_date" date NOT NULL,
	"from_date" date NOT NULL,
	"to_date" date NOT NULL,
	"fk_emp_id" varchar(50) NOT NULL,
	"bal_leave" varchar(20) DEFAULT '0',
	"bal_paid" varchar(20) DEFAULT '0',
	"bal_sick" varchar(20) DEFAULT '0',
	"bal_paid_casual" varchar(20) DEFAULT '0',
	"bal_unpaid_casual" varchar(20) DEFAULT '0',
	"rest_day" varchar(20) DEFAULT '0',
	"unpaid_leave" varchar(20) DEFAULT '0',
	"paid_holiday" varchar(20) DEFAULT '0',
	"sick_leave" varchar(20) DEFAULT '0',
	"paid_casual" varchar(20) DEFAULT '0',
	"unpaid_casual" varchar(20) DEFAULT '0',
	"maternity" varchar(20) DEFAULT '0',
	"paid_leave" varchar(20) DEFAULT '0',
	"total_leave" varchar(20) DEFAULT '0',
	"absent" varchar(20) DEFAULT '0',
	"reason" varchar(100),
	"remarks" varchar(100),
	"sys_defined" boolean DEFAULT false,
	"sync" varchar(5),
	"date_timestamp" timestamp,
	"fk_user_id" varchar(50),
	"last_status" varchar(30),
	"authorize" boolean DEFAULT false,
	"a_timestamp" timestamp,
	"fk_a_user_id" varchar(50),
	"accepted" varchar(10),
	"a_remarks" varchar(200),
	CONSTRAINT "uq_sal_lr_request_no" UNIQUE("request_no")
);
--> statement-breakpoint
CREATE TABLE "sal_lr_details" (
	"pk_lrd_id" varchar(50) PRIMARY KEY NOT NULL,
	"fk_lr_id" varchar(50) NOT NULL,
	"lr_date" date NOT NULL,
	"lr_day" varchar(20),
	"type" varchar(30),
	"typ_id" varchar(50)
);
--> statement-breakpoint
CREATE TABLE "hr_notification" (
	"pk_notif_id" varchar(50) PRIMARY KEY NOT NULL,
	"not_date" timestamp DEFAULT now() NOT NULL,
	"form_name" varchar(100) NOT NULL,
	"announcement" text,
	"file_name" varchar(255),
	"s_id" varchar(50),
	"n_id" varchar(50) NOT NULL,
	"edit_mode" smallint,
	"fk_user_id" varchar(50),
	"fk_set_id" varchar(50),
	"authorize" boolean DEFAULT false
);
--> statement-breakpoint
CREATE TABLE "temp_table" (
	"id" varchar(50) PRIMARY KEY NOT NULL,
	"temp_fields" varchar(100) NOT NULL
);
--> statement-breakpoint
ALTER TABLE "active_server" DROP CONSTRAINT "active_server_fk_book_id_account_book_pk_book_id_fk";
--> statement-breakpoint
ALTER TABLE "acct_group" ALTER COLUMN "pk_grp_id" SET GENERATED ALWAYS;--> statement-breakpoint
ALTER TABLE "app_user" ADD COLUMN "email" varchar(100);--> statement-breakpoint
ALTER TABLE "active_server" ADD COLUMN "email" varchar(100);--> statement-breakpoint
ALTER TABLE "active_server" ADD COLUMN "mobile" varchar(20);--> statement-breakpoint
ALTER TABLE "cont_common" ADD COLUMN "type" char(1) DEFAULT 'O' NOT NULL;--> statement-breakpoint
ALTER TABLE "cont_moc" ADD CONSTRAINT "cont_moc_fk_mt_id_cont_moc_type_pk_mt_id_fk" FOREIGN KEY ("fk_mt_id") REFERENCES "public"."cont_moc_type"("pk_mt_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cont_moc" ADD CONSTRAINT "cont_moc_fk_user_id_app_user_pk_user_id_fk" FOREIGN KEY ("fk_user_id") REFERENCES "public"."app_user"("pk_user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cont_region" ADD CONSTRAINT "cont_region_fk_user_id_app_user_pk_user_id_fk" FOREIGN KEY ("fk_user_id") REFERENCES "public"."app_user"("pk_user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cont_individual" ADD CONSTRAINT "cont_individual_fk_com_id_cont_common_pk_cont_id_fk" FOREIGN KEY ("fk_com_id") REFERENCES "public"."cont_common"("pk_cont_id") ON DELETE no action ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "cont_individual" ADD CONSTRAINT "cont_individual_fk_tit_id_cont_title_pk_tit_id_fk" FOREIGN KEY ("fk_tit_id") REFERENCES "public"."cont_title"("pk_tit_id") ON DELETE no action ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "cont_individual" ADD CONSTRAINT "cont_individual_fk_qual_id_cont_qualification_pk_qua_id_fk" FOREIGN KEY ("fk_qual_id") REFERENCES "public"."cont_qualification"("pk_qua_id") ON DELETE no action ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "cont_individual" ADD CONSTRAINT "cont_individual_fk_org_id_cont_common_pk_cont_id_fk" FOREIGN KEY ("fk_org_id") REFERENCES "public"."cont_common"("pk_cont_id") ON DELETE no action ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "cont_individual" ADD CONSTRAINT "cont_individual_fk_dep_id_cont_department_pk_dep_id_fk" FOREIGN KEY ("fk_dep_id") REFERENCES "public"."cont_department"("pk_dep_id") ON DELETE no action ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "cont_individual" ADD CONSTRAINT "cont_individual_fk_deg_id_cont_designation_pk_des_id_fk" FOREIGN KEY ("fk_deg_id") REFERENCES "public"."cont_designation"("pk_des_id") ON DELETE no action ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "cont_individual" ADD CONSTRAINT "cont_individual_fk_spo_id_cont_common_pk_cont_id_fk" FOREIGN KEY ("fk_spo_id") REFERENCES "public"."cont_common"("pk_cont_id") ON DELETE no action ON UPDATE cascade;--> statement-breakpoint
CREATE INDEX "idx_sal_annual_leave_emp_year" ON "sal_annual_leave" USING btree ("fk_emp_id","cal_year");--> statement-breakpoint
CREATE INDEX "idx_sal_leave_encashment_emp_year" ON "sal_leave_encashment" USING btree ("fk_emp_id","le_year");--> statement-breakpoint
CREATE INDEX "idx_sal_sel_holidays_ss" ON "sal_sel_holidays" USING btree ("fk_ss_id");--> statement-breakpoint
CREATE INDEX "idx_sal_sel_holidays_sh" ON "sal_sel_holidays" USING btree ("fk_sh_id");--> statement-breakpoint
CREATE INDEX "idx_sal_attendance_ss_date" ON "sal_attendance" USING btree ("fk_ss_id","at_date");--> statement-breakpoint
CREATE INDEX "idx_sal_attendance_w_type" ON "sal_attendance" USING btree ("w_type");--> statement-breakpoint
CREATE INDEX "idx_sal_m_atten_date_at" ON "sal_m_atten_date" USING btree ("fk_at_id");--> statement-breakpoint
CREATE INDEX "idx_sal_m_atten_date_w_type" ON "sal_m_atten_date" USING btree ("w_type");--> statement-breakpoint
CREATE INDEX "idx_sal_lr_request_date" ON "sal_leave_request" USING btree ("request_date");--> statement-breakpoint
CREATE INDEX "idx_sal_lr_fk_emp_id" ON "sal_leave_request" USING btree ("fk_emp_id");--> statement-breakpoint
CREATE INDEX "idx_sal_lr_fk_user_id" ON "sal_leave_request" USING btree ("fk_user_id");--> statement-breakpoint
CREATE INDEX "idx_sal_lr_authorize" ON "sal_leave_request" USING btree ("authorize");--> statement-breakpoint
CREATE INDEX "idx_sal_lr_details_fk_lr_id" ON "sal_lr_details" USING btree ("fk_lr_id");--> statement-breakpoint
CREATE INDEX "idx_hr_notification_form_nid" ON "hr_notification" USING btree ("form_name","n_id");--> statement-breakpoint
CREATE INDEX "idx_temp_table_id" ON "temp_table" USING btree ("id");