CREATE TABLE "sal_religion" (
	"pk_rg_id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "sal_religion_pk_rg_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"religion" varchar(50),
	"sync" char(1),
	"sys_defined" boolean,
	"date_time_stamp" timestamp,
	"fk_user_id" integer,
	"last_status" varchar(10)
);
--> statement-breakpoint
CREATE TABLE "sal_castes" (
	"pk_cs_id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "sal_castes_pk_cs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"caste" varchar(40),
	"sync" char(1),
	"sys_defined" boolean,
	"date_time_stamp" timestamp,
	"fk_user_id" integer,
	"last_status" varchar(10)
);
--> statement-breakpoint
CREATE TABLE "sal_schedule_type" (
	"pk_st_id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "sal_schedule_type_pk_st_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"type" varchar(100),
	"sync" char(1),
	"sys_defined" boolean,
	"date_time_stamp" timestamp,
	"fk_user_id" integer,
	"last_status" varchar(10)
);
--> statement-breakpoint
CREATE TABLE "sal_skintone" (
	"pk_st_id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "sal_skintone_pk_st_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"colour" varchar(25),
	"sync" char(1),
	"sys_defined" boolean,
	"date_time_stamp" timestamp,
	"fk_user_id" integer,
	"last_status" varchar(10)
);
--> statement-breakpoint
CREATE TABLE "sal_nature_of_work" (
	"pk_nw_id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "sal_nature_of_work_pk_nw_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"nature_of_work" varchar(40) NOT NULL,
	"sync" char(1),
	"sys_defined" boolean DEFAULT false,
	"date_timestamp" timestamp,
	"fk_user_id" integer,
	"last_status" varchar(10)
);
--> statement-breakpoint
CREATE TABLE "sal_it_section" (
	"pk_sec_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sal_it_section_pk_sec_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"it_section" varchar(75) NOT NULL,
	"deduction" numeric(18, 2),
	"fk_fy_id" integer,
	"sync" varchar(1),
	"sys_defined" boolean DEFAULT false,
	"date_time_stamp" timestamp DEFAULT now(),
	"fk_user_id" integer,
	"last_status" varchar(10),
	"additraction" varchar(12)
);
--> statement-breakpoint
CREATE TABLE "sal_emp_contact" (
	"pk_cont_id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "sal_emp_contact_pk_cont_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"fk_emp_id" integer NOT NULL,
	"fk_moc_id" char(5) NOT NULL,
	"contact" varchar(50) NOT NULL,
	"ext" varchar(10) NOT NULL,
	"sr_no" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sal_emp_documents" (
	"pk_d_emp_id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "sal_emp_documents_pk_d_emp_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"fk_emp_id" integer NOT NULL,
	"fk_dt_id" integer NOT NULL,
	"doc_file" varchar(100) NOT NULL,
	"valid_until" timestamp
);
--> statement-breakpoint
CREATE TABLE "cont_moc" (
	"pk_moc_id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "cont_moc_pk_moc_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"moc" varchar(25) NOT NULL,
	"fk_mt_id" integer NOT NULL,
	"sync" char(1) NOT NULL,
	"sys_defined" boolean DEFAULT false NOT NULL,
	"date_timestamp" timestamp NOT NULL,
	"fk_user_id" integer NOT NULL,
	"last_status" varchar(10) NOT NULL,
	CONSTRAINT "ix_cont_moc" UNIQUE("moc")
);
--> statement-breakpoint
CREATE TABLE "cont_moc_type" (
	"pk_mt_id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "cont_moc_type_pk_mt_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"mode" varchar(6) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cont_country" (
	"pk_ctry_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cont_country_pk_ctry_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"country" varchar(50) NOT NULL,
	"isd_code" varchar(20) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cont_state" (
	"pk_state_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cont_state_pk_state_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"state" varchar(30) NOT NULL,
	"fk_ctry_id" integer NOT NULL,
	"state_code" varchar(10) DEFAULT '' NOT NULL,
	"sync" char(1) DEFAULT 'N' NOT NULL,
	"sys_defined" boolean DEFAULT false NOT NULL,
	"date_time_stamp" timestamp DEFAULT now() NOT NULL,
	"fk_user_id" integer NOT NULL,
	"last_status" varchar(10) DEFAULT '' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cont_city" (
	"pk_city_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cont_city_pk_city_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"city" varchar(30) NOT NULL,
	"fk_state_id" integer,
	"fk_ctry_id" integer NOT NULL,
	"std_code" varchar(10) DEFAULT '' NOT NULL,
	"sync" char(1) DEFAULT 'N' NOT NULL,
	"sys_defined" boolean DEFAULT false NOT NULL,
	"date_time_stamp" timestamp DEFAULT now() NOT NULL,
	"fk_user_id" integer NOT NULL,
	"last_status" varchar(10) DEFAULT '' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cont_address" (
	"pk_ca_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cont_address_pk_ca_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"fk_cont_id" integer,
	"address" varchar(150) NOT NULL,
	"fk_city_id" integer,
	"region" varchar(50) DEFAULT '' NOT NULL,
	"pincode" varchar(50),
	"sync" char(1) DEFAULT 'N' NOT NULL,
	"sys_defined" boolean DEFAULT false NOT NULL,
	"date_time_stamp" timestamp DEFAULT now() NOT NULL,
	"fk_user_id" integer NOT NULL,
	"last_status" varchar(10) DEFAULT '' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cont_common" (
	"pk_cont_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cont_common_pk_cont_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"type" char(1) DEFAULT 'O' NOT NULL,
	"contact_name" varchar(50) NOT NULL,
	"address" varchar(150) DEFAULT '' NOT NULL,
	"fk_city_id" integer,
	"region" varchar(50) DEFAULT '' NOT NULL,
	"pincode" varchar(50),
	"sync" char(1) DEFAULT 'N' NOT NULL,
	"sys_defined" boolean DEFAULT false NOT NULL,
	"date_time_stamp" timestamp DEFAULT now() NOT NULL,
	"fk_user_id" integer,
	"last_status" varchar(10) DEFAULT '' NOT NULL,
	"postfix" varchar(25) DEFAULT '' NOT NULL,
	"fk_emp_id" integer,
	"fk_a_user_id" integer,
	"a_timestamp" timestamp,
	"username" varchar(40),
	"password" varchar(20),
	"question" varchar(50),
	"answer" varchar(50),
	"client_id" varchar(30) DEFAULT '' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cont_region" (
	"pk_reg_id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "cont_region_pk_reg_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"region" varchar(30) NOT NULL,
	"rate1" numeric(19, 2) NOT NULL,
	"rate2" numeric(19, 2) NOT NULL,
	"sync" char(1) NOT NULL,
	"sys_defined" boolean DEFAULT false NOT NULL,
	"date_timestamp" timestamp NOT NULL,
	"fk_user_id" integer NOT NULL,
	"last_status" varchar(10) NOT NULL,
	CONSTRAINT "ix_cont_region" UNIQUE("region")
);
--> statement-breakpoint
CREATE TABLE "cont_individual" (
	"pk_ind_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cont_individual_pk_ind_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"fk_com_id" integer NOT NULL,
	"fk_tit_id" integer,
	"first_name" varchar(50) NOT NULL,
	"middle_name" varchar(40) DEFAULT '' NOT NULL,
	"surname" varchar(25) NOT NULL,
	"dob" timestamp,
	"photo_url" varchar(500),
	"fk_qual_id" integer,
	"gender" varchar(25) DEFAULT '',
	"marital_status" varchar(25) DEFAULT 'single' NOT NULL,
	"fk_org_id" integer,
	"fk_dep_id" integer,
	"fk_deg_id" integer,
	"fk_spo_id" integer,
	"anniversary" timestamp,
	"ext" varchar(10)
);
--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP CONSTRAINT "sal_attendance_fk_ss_id_sal_structure_pk_ss_id_fk";
--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP CONSTRAINT "sal_attendance_fk_st_id_sal_shift_timing_pk_st_id_fk";
--> statement-breakpoint
ALTER TABLE "sal_structure" DROP CONSTRAINT "sal_structure_fk_emp_id_sal_employee_pk_emp_id_fk";
--> statement-breakpoint
ALTER TABLE "app_user" ALTER COLUMN "password" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "account_book" ALTER COLUMN "pk_book_id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "account_book" ALTER COLUMN "pk_book_id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "account_book_pk_book_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "active_server" ALTER COLUMN "fk_book_id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "sal_employee" ALTER COLUMN "pk_emp_id" SET GENERATED BY DEFAULT;--> statement-breakpoint
ALTER TABLE "sal_employee" ALTER COLUMN "fk_tit_id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "sal_employee" ALTER COLUMN "fk_qual_id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "sal_employee" ALTER COLUMN "fk_dep_id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "sal_employee" ALTER COLUMN "fk_deg_id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "sal_employee" ALTER COLUMN "fk_bnk_id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "sal_employee" ALTER COLUMN "password" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "sal_employee" ALTER COLUMN "fk_user_id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "sal_employee" ALTER COLUMN "fk_set_id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "sal_employee" ALTER COLUMN "fk_p1_des_id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "sal_employee" ALTER COLUMN "fk_p2_des_id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "sal_employee" ALTER COLUMN "fk_acct_id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "email_configuration" ALTER COLUMN "fk_user_id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "sal_attendance" ALTER COLUMN "pk_at_id" SET DATA TYPE varchar(50);--> statement-breakpoint
ALTER TABLE "sal_attendance" ALTER COLUMN "pk_at_id" DROP IDENTITY;--> statement-breakpoint
ALTER TABLE "sal_attendance" ALTER COLUMN "fk_ss_id" SET DATA TYPE varchar(50);--> statement-breakpoint
ALTER TABLE "sal_attendance" ALTER COLUMN "at_date" SET DATA TYPE date;--> statement-breakpoint
ALTER TABLE "sal_attendance" ALTER COLUMN "w_type" SET DATA TYPE varchar(50);--> statement-breakpoint
ALTER TABLE "sal_attendance" ALTER COLUMN "authorize" SET DEFAULT false;--> statement-breakpoint
ALTER TABLE "sal_leave_request" ALTER COLUMN "pk_lr_id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "sal_leave_request" ALTER COLUMN "pk_lr_id" ADD GENERATED ALWAYS AS IDENTITY (sequence name "sal_leave_request_pk_lr_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "sal_leave_request" ALTER COLUMN "fk_emp_id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "sal_leave_request" ALTER COLUMN "fk_user_id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "sal_leave_request" ALTER COLUMN "fk_a_user_id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "sal_lr_details" ALTER COLUMN "pk_lrd_id" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sal_lr_details" ALTER COLUMN "pk_lrd_id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "sal_lr_details_pk_lrd_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "sal_lr_details" ALTER COLUMN "fk_lr_id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "hr_notification" ALTER COLUMN "pk_notif_id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "hr_notification" ALTER COLUMN "pk_notif_id" ADD GENERATED ALWAYS AS IDENTITY (sequence name "hr_notification_pk_notif_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "hr_notification" ALTER COLUMN "n_id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "hr_notification" ALTER COLUMN "fk_user_id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "sal_loan" ALTER COLUMN "pk_loan_id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "sal_loan" ALTER COLUMN "pk_loan_id" ADD GENERATED ALWAYS AS IDENTITY (sequence name "sal_loan_pk_loan_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "sal_loan" ALTER COLUMN "fk_emp_id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "sal_loan" ALTER COLUMN "fk_user_id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "sal_loan" ALTER COLUMN "fk_a_user_id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "sal_loan_schedule" ALTER COLUMN "pk_schedule_id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "sal_loan_schedule" ALTER COLUMN "pk_schedule_id" ADD GENERATED ALWAYS AS IDENTITY (sequence name "sal_loan_schedule_pk_schedule_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "sal_loan_schedule" ALTER COLUMN "fk_loan_id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "sal_structure" ALTER COLUMN "pk_ss_id" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "sal_structure" ALTER COLUMN "pk_ss_id" DROP IDENTITY;--> statement-breakpoint
ALTER TABLE "sal_structure" ALTER COLUMN "fk_emp_id" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "sal_structure" ALTER COLUMN "sl" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "sal_structure" ALTER COLUMN "sl" SET DEFAULT '0';--> statement-breakpoint
ALTER TABLE "sal_structure" ALTER COLUMN "cl" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "sal_structure" ALTER COLUMN "cl" SET DEFAULT '0';--> statement-breakpoint
ALTER TABLE "sal_structure" ALTER COLUMN "ucl" SET DATA TYPE numeric;--> statement-breakpoint
ALTER TABLE "sal_structure" ALTER COLUMN "ucl" SET DEFAULT '0';--> statement-breakpoint
ALTER TABLE "sal_structure" ALTER COLUMN "sandwich" SET DEFAULT false;--> statement-breakpoint
ALTER TABLE "account_book" ADD COLUMN "database_name" varchar(50) NOT NULL;--> statement-breakpoint
ALTER TABLE "sal_employee" ADD COLUMN "gender" varchar(10) NOT NULL;--> statement-breakpoint
ALTER TABLE "sal_employee" ADD COLUMN "martial_status" varchar(15) NOT NULL;--> statement-breakpoint
ALTER TABLE "sal_structure" ADD COLUMN "r_day_i" varchar(20);--> statement-breakpoint
ALTER TABLE "sal_structure" ADD COLUMN "r_day_ii" varchar(20);--> statement-breakpoint
ALTER TABLE "sal_religion" ADD CONSTRAINT "sal_religion_fk_user_id_app_user_pk_user_id_fk" FOREIGN KEY ("fk_user_id") REFERENCES "public"."app_user"("pk_user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sal_castes" ADD CONSTRAINT "sal_castes_fk_user_id_app_user_pk_user_id_fk" FOREIGN KEY ("fk_user_id") REFERENCES "public"."app_user"("pk_user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sal_schedule_type" ADD CONSTRAINT "sal_schedule_type_fk_user_id_app_user_pk_user_id_fk" FOREIGN KEY ("fk_user_id") REFERENCES "public"."app_user"("pk_user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sal_skintone" ADD CONSTRAINT "sal_skintone_fk_user_id_app_user_pk_user_id_fk" FOREIGN KEY ("fk_user_id") REFERENCES "public"."app_user"("pk_user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cont_moc" ADD CONSTRAINT "cont_moc_fk_mt_id_cont_moc_type_pk_mt_id_fk" FOREIGN KEY ("fk_mt_id") REFERENCES "public"."cont_moc_type"("pk_mt_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cont_moc" ADD CONSTRAINT "cont_moc_fk_user_id_app_user_pk_user_id_fk" FOREIGN KEY ("fk_user_id") REFERENCES "public"."app_user"("pk_user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cont_state" ADD CONSTRAINT "cont_state_fk_ctry_id_cont_country_pk_ctry_id_fk" FOREIGN KEY ("fk_ctry_id") REFERENCES "public"."cont_country"("pk_ctry_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cont_state" ADD CONSTRAINT "cont_state_fk_user_id_app_user_pk_user_id_fk" FOREIGN KEY ("fk_user_id") REFERENCES "public"."app_user"("pk_user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cont_city" ADD CONSTRAINT "cont_city_fk_state_id_cont_state_pk_state_id_fk" FOREIGN KEY ("fk_state_id") REFERENCES "public"."cont_state"("pk_state_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cont_city" ADD CONSTRAINT "cont_city_fk_ctry_id_cont_country_pk_ctry_id_fk" FOREIGN KEY ("fk_ctry_id") REFERENCES "public"."cont_country"("pk_ctry_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cont_city" ADD CONSTRAINT "cont_city_fk_user_id_app_user_pk_user_id_fk" FOREIGN KEY ("fk_user_id") REFERENCES "public"."app_user"("pk_user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cont_address" ADD CONSTRAINT "cont_address_fk_cont_id_cont_common_pk_cont_id_fk" FOREIGN KEY ("fk_cont_id") REFERENCES "public"."cont_common"("pk_cont_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cont_address" ADD CONSTRAINT "cont_address_fk_city_id_cont_city_pk_city_id_fk" FOREIGN KEY ("fk_city_id") REFERENCES "public"."cont_city"("pk_city_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cont_address" ADD CONSTRAINT "cont_address_fk_user_id_app_user_pk_user_id_fk" FOREIGN KEY ("fk_user_id") REFERENCES "public"."app_user"("pk_user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cont_common" ADD CONSTRAINT "cont_common_fk_city_id_cont_city_pk_city_id_fk" FOREIGN KEY ("fk_city_id") REFERENCES "public"."cont_city"("pk_city_id") ON DELETE no action ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "cont_common" ADD CONSTRAINT "cont_common_fk_user_id_app_user_pk_user_id_fk" FOREIGN KEY ("fk_user_id") REFERENCES "public"."app_user"("pk_user_id") ON DELETE no action ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "cont_common" ADD CONSTRAINT "cont_common_fk_emp_id_sal_employee_pk_emp_id_fk" FOREIGN KEY ("fk_emp_id") REFERENCES "public"."sal_employee"("pk_emp_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cont_common" ADD CONSTRAINT "cont_common_fk_a_user_id_app_user_pk_user_id_fk" FOREIGN KEY ("fk_a_user_id") REFERENCES "public"."app_user"("pk_user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cont_region" ADD CONSTRAINT "cont_region_fk_user_id_app_user_pk_user_id_fk" FOREIGN KEY ("fk_user_id") REFERENCES "public"."app_user"("pk_user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cont_individual" ADD CONSTRAINT "cont_individual_fk_com_id_cont_common_pk_cont_id_fk" FOREIGN KEY ("fk_com_id") REFERENCES "public"."cont_common"("pk_cont_id") ON DELETE no action ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "cont_individual" ADD CONSTRAINT "cont_individual_fk_tit_id_cont_title_pk_tit_id_fk" FOREIGN KEY ("fk_tit_id") REFERENCES "public"."cont_title"("pk_tit_id") ON DELETE no action ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "cont_individual" ADD CONSTRAINT "cont_individual_fk_qual_id_cont_qualification_pk_qua_id_fk" FOREIGN KEY ("fk_qual_id") REFERENCES "public"."cont_qualification"("pk_qua_id") ON DELETE no action ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "cont_individual" ADD CONSTRAINT "cont_individual_fk_org_id_cont_common_pk_cont_id_fk" FOREIGN KEY ("fk_org_id") REFERENCES "public"."cont_common"("pk_cont_id") ON DELETE no action ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "cont_individual" ADD CONSTRAINT "cont_individual_fk_dep_id_cont_department_pk_dep_id_fk" FOREIGN KEY ("fk_dep_id") REFERENCES "public"."cont_department"("pk_dep_id") ON DELETE no action ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "cont_individual" ADD CONSTRAINT "cont_individual_fk_deg_id_cont_designation_pk_des_id_fk" FOREIGN KEY ("fk_deg_id") REFERENCES "public"."cont_designation"("pk_des_id") ON DELETE no action ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "cont_individual" ADD CONSTRAINT "cont_individual_fk_spo_id_cont_common_pk_cont_id_fk" FOREIGN KEY ("fk_spo_id") REFERENCES "public"."cont_common"("pk_cont_id") ON DELETE no action ON UPDATE cascade;--> statement-breakpoint
CREATE INDEX "ix_cont_city_city" ON "cont_city" USING btree ("city");--> statement-breakpoint
ALTER TABLE "active_server" ADD CONSTRAINT "active_server_fk_book_id_account_book_pk_book_id_fk" FOREIGN KEY ("fk_book_id") REFERENCES "public"."account_book"("pk_book_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sal_employee" ADD CONSTRAINT "sal_employee_fk_tit_id_cont_title_pk_tit_id_fk" FOREIGN KEY ("fk_tit_id") REFERENCES "public"."cont_title"("pk_tit_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sal_employee" ADD CONSTRAINT "sal_employee_fk_qual_id_cont_qualification_pk_qua_id_fk" FOREIGN KEY ("fk_qual_id") REFERENCES "public"."cont_qualification"("pk_qua_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sal_employee" ADD CONSTRAINT "sal_employee_fk_dep_id_cont_department_pk_dep_id_fk" FOREIGN KEY ("fk_dep_id") REFERENCES "public"."cont_department"("pk_dep_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sal_employee" ADD CONSTRAINT "sal_employee_fk_deg_id_cont_designation_pk_des_id_fk" FOREIGN KEY ("fk_deg_id") REFERENCES "public"."cont_designation"("pk_des_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sal_employee" ADD CONSTRAINT "sal_employee_fk_user_id_app_user_pk_user_id_fk" FOREIGN KEY ("fk_user_id") REFERENCES "public"."app_user"("pk_user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sal_employee" ADD CONSTRAINT "sal_employee_fk_p1_des_id_cont_designation_pk_des_id_fk" FOREIGN KEY ("fk_p1_des_id") REFERENCES "public"."cont_designation"("pk_des_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sal_employee" ADD CONSTRAINT "sal_employee_fk_p2_des_id_cont_designation_pk_des_id_fk" FOREIGN KEY ("fk_p2_des_id") REFERENCES "public"."cont_designation"("pk_des_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "email_configuration" ADD CONSTRAINT "email_configuration_fk_user_id_app_user_pk_user_id_fk" FOREIGN KEY ("fk_user_id") REFERENCES "public"."app_user"("pk_user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_sal_attendance_ss_date" ON "sal_attendance" USING btree ("fk_ss_id","at_date");--> statement-breakpoint
CREATE INDEX "idx_sal_attendance_w_type" ON "sal_attendance" USING btree ("w_type");--> statement-breakpoint
CREATE INDEX "idx_sal_structure_emp" ON "sal_structure" USING btree ("fk_emp_id");--> statement-breakpoint
CREATE INDEX "idx_sal_structure_dates" ON "sal_structure" USING btree ("sal_start","revise");--> statement-breakpoint
ALTER TABLE "account_book" DROP COLUMN "database_nar";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "male";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "married";--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP COLUMN "time_in";--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP COLUMN "time_out";--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP COLUMN "m_break";--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP COLUMN "w_hour";--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP COLUMN "aw_hour";--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP COLUMN "overtime";--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP COLUMN "bot";--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP COLUMN "cal_ot";--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP COLUMN "remarks";--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP COLUMN "sync";--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP COLUMN "sys_defined";--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP COLUMN "date_time_stamp";--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP COLUMN "fk_user_id";--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP COLUMN "last_status";--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP COLUMN "a_timestamp";--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP COLUMN "fk_a_user_id";--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP COLUMN "a_hour";--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP COLUMN "pw";--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP COLUMN "late_mark";--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP COLUMN "uh1";--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP COLUMN "fk_at1_id";--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP COLUMN "uh2";--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP COLUMN "fk_at2_id";--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP COLUMN "uh3";--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP COLUMN "fk_at3_id";--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP COLUMN "f_apply";--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP COLUMN "extra_hours";--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP COLUMN "imp_status";--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP COLUMN "latitude";--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP COLUMN "longitude";--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP COLUMN "min_late";--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP COLUMN "min_plenty";--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP COLUMN "inf_late";--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP COLUMN "min_early";--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP COLUMN "inf_early";--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP COLUMN "break_time";--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP COLUMN "at_time_in";--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP COLUMN "at_time_out";--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP COLUMN "m_time_in";--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP COLUMN "m_time_out";--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP COLUMN "s_time_in";--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP COLUMN "s_time_out";--> statement-breakpoint
ALTER TABLE "sal_attendance" DROP COLUMN "fk_st_id";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "basic";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "b_type";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "allowance";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "t_allowance";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "travelling";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "t_travelling";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "housing";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "t_housing";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "daily";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "t_daily";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "incentive";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "t_incentive";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "education";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "t_education";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "medical";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "t_medical";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "other";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "t_other";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "oti";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "toti";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "otii";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "totii";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "rday_i";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "rday_ii";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "ph";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "wh";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "rwh";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "bl";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "bld";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "a_rule";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "otb";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "cal_pt";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "cal_pf";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "cal_esic";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "cal_tds";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "slab_tds";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "scan_mb";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "fk_sacct_id";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "remarks";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "sync";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "sys_defined";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "date_time_stamp";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "fk_user_id";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "last_status";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "other_basic";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "eot";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "ew_hour";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "lyew_hour";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "fk_lacct_id";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "ma_basic";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "ea_basic";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "incentive_basic";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "da_basic";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "ha_basic";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "ta_basic";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "allowance_basic";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "fk_fcont_id";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "fk_tcont_id";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "sal_gross";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "fk_iacct_id";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "ab_penalty";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "variant";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "pfa";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "pfta";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "pfha";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "pfi";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "pfea";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "pfma";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "pfoa";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "rd_variant";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "retention";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "fk_emp1_id";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "fk_emp2_id";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "fk_racct_id";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "sal_daily";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "set_pf";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "gha";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "rda";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "iorf";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "oaop";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "ltime_roff";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "latitude";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "longitude";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "tds_deduct";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "m_deduction";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "ded_description";--> statement-breakpoint
ALTER TABLE "sal_structure" DROP COLUMN "fk_des_id";