ALTER TABLE "account_book" ALTER COLUMN "pk_book_id" SET GENERATED BY DEFAULT;--> statement-breakpoint
ALTER TABLE "account_book" ALTER COLUMN "product_id" SET DATA TYPE numeric(18, 0);--> statement-breakpoint
ALTER TABLE "sal_employee" ALTER COLUMN "fk_tit_id" SET DATA TYPE integer USING "fk_tit_id"::integer;--> statement-breakpoint
ALTER TABLE "sal_employee" ALTER COLUMN "fk_qual_id" SET DATA TYPE integer USING "fk_qual_id"::integer;--> statement-breakpoint
ALTER TABLE "sal_employee" ALTER COLUMN "fk_dep_id" SET DATA TYPE integer USING "fk_dep_id"::integer;--> statement-breakpoint
ALTER TABLE "sal_employee" ALTER COLUMN "fk_deg_id" SET DATA TYPE integer USING "fk_deg_id"::integer;--> statement-breakpoint
ALTER TABLE "sal_employee" ALTER COLUMN "fk_bnk_id" SET DATA TYPE integer USING "fk_bnk_id"::integer;--> statement-breakpoint
ALTER TABLE "sal_employee" ALTER COLUMN "fk_user_id" SET DATA TYPE integer USING "fk_user_id"::integer;--> statement-breakpoint
ALTER TABLE "sal_employee" ALTER COLUMN "fk_set_id" SET DATA TYPE integer USING "fk_set_id"::integer;--> statement-breakpoint
ALTER TABLE "sal_employee" ALTER COLUMN "fk_p1_des_id" SET DATA TYPE integer USING "fk_p1_des_id"::integer;--> statement-breakpoint
ALTER TABLE "sal_employee" ALTER COLUMN "fk_p2_des_id" SET DATA TYPE integer USING "fk_p2_des_id"::integer;--> statement-breakpoint
ALTER TABLE "sal_employee" ALTER COLUMN "fk_acct_id" SET DATA TYPE integer USING "fk_acct_id"::integer;--> statement-breakpoint
ALTER TABLE "email_configuration" ALTER COLUMN "fk_user_id" SET DATA TYPE integer USING "fk_user_id"::integer;--> statement-breakpoint
ALTER TABLE "sal_religion" ALTER COLUMN "fk_user_id" SET DATA TYPE integer USING "fk_user_id"::integer;--> statement-breakpoint
ALTER TABLE "sal_castes" ALTER COLUMN "fk_user_id" SET DATA TYPE integer USING "fk_user_id"::integer;--> statement-breakpoint
ALTER TABLE "sal_schedule_type" ALTER COLUMN "fk_user_id" SET DATA TYPE integer USING "fk_user_id"::integer;--> statement-breakpoint
ALTER TABLE "sal_skintone" ALTER COLUMN "fk_user_id" SET DATA TYPE integer USING "fk_user_id"::integer;--> statement-breakpoint
ALTER TABLE "sal_employee" ADD CONSTRAINT "sal_employee_fk_tit_id_cont_title_pk_tit_id_fk" FOREIGN KEY ("fk_tit_id") REFERENCES "public"."cont_title"("pk_tit_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sal_employee" ADD CONSTRAINT "sal_employee_fk_qual_id_cont_qualification_pk_qua_id_fk" FOREIGN KEY ("fk_qual_id") REFERENCES "public"."cont_qualification"("pk_qua_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sal_employee" ADD CONSTRAINT "sal_employee_fk_dep_id_cont_department_pk_dep_id_fk" FOREIGN KEY ("fk_dep_id") REFERENCES "public"."cont_department"("pk_dep_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sal_employee" ADD CONSTRAINT "sal_employee_fk_deg_id_cont_designation_pk_des_id_fk" FOREIGN KEY ("fk_deg_id") REFERENCES "public"."cont_designation"("pk_des_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sal_employee" ADD CONSTRAINT "sal_employee_fk_user_id_app_user_pk_user_id_fk" FOREIGN KEY ("fk_user_id") REFERENCES "public"."app_user"("pk_user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sal_employee" ADD CONSTRAINT "sal_employee_fk_p1_des_id_cont_designation_pk_des_id_fk" FOREIGN KEY ("fk_p1_des_id") REFERENCES "public"."cont_designation"("pk_des_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sal_employee" ADD CONSTRAINT "sal_employee_fk_p2_des_id_cont_designation_pk_des_id_fk" FOREIGN KEY ("fk_p2_des_id") REFERENCES "public"."cont_designation"("pk_des_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "email_configuration" ADD CONSTRAINT "email_configuration_fk_user_id_app_user_pk_user_id_fk" FOREIGN KEY ("fk_user_id") REFERENCES "public"."app_user"("pk_user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sal_religion" ADD CONSTRAINT "sal_religion_fk_user_id_app_user_pk_user_id_fk" FOREIGN KEY ("fk_user_id") REFERENCES "public"."app_user"("pk_user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sal_castes" ADD CONSTRAINT "sal_castes_fk_user_id_app_user_pk_user_id_fk" FOREIGN KEY ("fk_user_id") REFERENCES "public"."app_user"("pk_user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sal_schedule_type" ADD CONSTRAINT "sal_schedule_type_fk_user_id_app_user_pk_user_id_fk" FOREIGN KEY ("fk_user_id") REFERENCES "public"."app_user"("pk_user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sal_skintone" ADD CONSTRAINT "sal_skintone_fk_user_id_app_user_pk_user_id_fk" FOREIGN KEY ("fk_user_id") REFERENCES "public"."app_user"("pk_user_id") ON DELETE no action ON UPDATE no action;