CREATE TABLE "sal_it_section" (
	"pk_sec_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sal_it_section_pk_sec_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"it_section" varchar(75) NOT NULL,
	"deduction" numeric(18, 2),
	"fk_fy_id" integer,
	"sync" varchar(1),
	"sys_defined" boolean DEFAULT false,
	"date_timestamp" timestamp DEFAULT now(),
	"fk_user_id" integer,
	"last_status" varchar(10),
	"additraction" varchar(12)
);
