CREATE TABLE "sal_office_boy" (
	"pk_ob_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sal_office_boy_pk_ob_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"mobile" varchar(15),
	"email" varchar(100),
	"address" text,
	"fk_user_id" integer,
	"date_time_stamp" timestamp DEFAULT now() NOT NULL,
	"last_status" varchar(10) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sal_office_boy_task" (
	"pk_task_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sal_office_boy_task_pk_task_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"task_name" varchar(500) NOT NULL,
	"reaching_date" varchar(20) NOT NULL,
	"reaching_time" varchar(10) NOT NULL,
	"status" varchar(20) DEFAULT 'Pending' NOT NULL,
	"date_time_stamp" timestamp DEFAULT now() NOT NULL,
	"fk_user_id" integer NOT NULL,
	"fk_ob_id" integer
);
--> statement-breakpoint
CREATE TABLE "audit_log" (
	"pk_audit_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "audit_log_pk_audit_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"action" varchar(50) NOT NULL,
	"resource" varchar(100) NOT NULL,
	"resource_id" integer,
	"old_values" jsonb,
	"new_values" jsonb,
	"user_id" varchar(50),
	"user_ip" varchar(45),
	"user_agent" varchar(255),
	"timestamp" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "file_metadata" (
	"pk_file_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "file_metadata_pk_file_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"announcement_id" integer,
	"file_name" varchar(255) NOT NULL,
	"file_size" integer NOT NULL,
	"mime_type" varchar(100) NOT NULL,
	"storage_path" varchar(500) NOT NULL,
	"virus_scanned" boolean DEFAULT false NOT NULL,
	"scan_result" varchar(255),
	"uploaded_by" varchar(50),
	"uploaded_at" timestamp with time zone DEFAULT now() NOT NULL,
	"accessed_count" integer DEFAULT 0 NOT NULL,
	"last_accessed" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "hr_announcement" (
	"pk_an_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hr_announcement_pk_an_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ref_no" varchar(20) NOT NULL,
	"ref_date" timestamp NOT NULL,
	"fk_nt_id" integer NOT NULL,
	"announcement" text NOT NULL,
	"file_name" varchar(255),
	"sys_defined" boolean DEFAULT false,
	"date_timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"fk_user_id" integer NOT NULL,
	"last_status" varchar(50) DEFAULT 'Added',
	"authorize" boolean DEFAULT false,
	"a_timestamp" timestamp with time zone,
	"fk_a_user_id" integer,
	"sync" char(1) DEFAULT 'N',
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "hr_emp_announcement" (
	"pk_san_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hr_emp_announcement_pk_san_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"fk_an_id" integer NOT NULL,
	"fk_ss_id" numeric NOT NULL
);
--> statement-breakpoint
CREATE TABLE "hr_notice_type" (
	"pk_nt_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hr_notice_type_pk_nt_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"type" varchar(100) NOT NULL,
	"sync" char(1) DEFAULT 'N',
	CONSTRAINT "hr_notice_type_type_unique" UNIQUE("type")
);
--> statement-breakpoint
CREATE TABLE "notification_log" (
	"pk_notif_log_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "notification_log_pk_notif_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"announcement_id" integer,
	"user_id" varchar(50),
	"channel" varchar(50) NOT NULL,
	"status" varchar(50) NOT NULL,
	"sent_at" timestamp with time zone DEFAULT now() NOT NULL,
	"delivered_at" timestamp with time zone,
	"error_message" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "sync_log" (
	"pk_sync_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sync_log_pk_sync_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"announcement_id" integer,
	"destination" varchar(50) NOT NULL,
	"status" varchar(50) NOT NULL,
	"sync_data" jsonb,
	"error" text,
	"attempted_at" timestamp with time zone DEFAULT now() NOT NULL,
	"completed_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "sal_employee" DROP CONSTRAINT "sal_employee_fk_tit_id_cont_title_pk_tit_id_fk";
--> statement-breakpoint
ALTER TABLE "sal_employee" DROP CONSTRAINT "sal_employee_fk_qual_id_cont_qualification_pk_qua_id_fk";
--> statement-breakpoint
ALTER TABLE "sal_employee" DROP CONSTRAINT "sal_employee_fk_dep_id_cont_department_pk_dep_id_fk";
--> statement-breakpoint
ALTER TABLE "sal_employee" DROP CONSTRAINT "sal_employee_fk_deg_id_cont_designation_pk_des_id_fk";
--> statement-breakpoint
ALTER TABLE "sal_employee" DROP CONSTRAINT "sal_employee_fk_user_id_app_user_pk_user_id_fk";
--> statement-breakpoint
ALTER TABLE "sal_employee" DROP CONSTRAINT "sal_employee_fk_p1_des_id_cont_designation_pk_des_id_fk";
--> statement-breakpoint
ALTER TABLE "sal_employee" DROP CONSTRAINT "sal_employee_fk_p2_des_id_cont_designation_pk_des_id_fk";
--> statement-breakpoint
ALTER TABLE "attendance_locations" ALTER COLUMN "allowed_radius" SET DEFAULT '25.00';--> statement-breakpoint
ALTER TABLE "sal_employee" ALTER COLUMN "emp_code" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "sal_employee" ALTER COLUMN "employee" SET DATA TYPE varchar(150);--> statement-breakpoint
ALTER TABLE "sal_employee" ALTER COLUMN "employee" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "sal_employee" ALTER COLUMN "doj" SET DATA TYPE date;--> statement-breakpoint
ALTER TABLE "sal_employee" ALTER COLUMN "doj" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "sal_employee" ALTER COLUMN "fk_dep_id" SET DATA TYPE varchar(50);--> statement-breakpoint
ALTER TABLE "sal_employee" ALTER COLUMN "fk_deg_id" SET DATA TYPE varchar(50);--> statement-breakpoint
ALTER TABLE "sal_employee" ALTER COLUMN "fk_set_id" SET DATA TYPE varchar(50);--> statement-breakpoint
ALTER TABLE "sal_employee" ALTER COLUMN "type" SET DATA TYPE varchar(50);--> statement-breakpoint
ALTER TABLE "sal_employee" ALTER COLUMN "type" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "sal_annual_leave" ALTER COLUMN "pk_sal_id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "sal_annual_leave" ALTER COLUMN "pk_sal_id" ADD GENERATED ALWAYS AS IDENTITY (sequence name "sal_annual_leave_pk_sal_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "sal_annual_leave" ALTER COLUMN "al_roff" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "sal_annual_leave" ALTER COLUMN "py_bal" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "sal_annual_leave" ALTER COLUMN "tot_al" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "sal_office_boy_task" ADD CONSTRAINT "sal_office_boy_task_fk_ob_id_sal_office_boy_pk_ob_id_fk" FOREIGN KEY ("fk_ob_id") REFERENCES "public"."sal_office_boy"("pk_ob_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "file_metadata" ADD CONSTRAINT "file_metadata_announcement_id_hr_announcement_pk_an_id_fk" FOREIGN KEY ("announcement_id") REFERENCES "public"."hr_announcement"("pk_an_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hr_announcement" ADD CONSTRAINT "hr_announcement_fk_nt_id_hr_notice_type_pk_nt_id_fk" FOREIGN KEY ("fk_nt_id") REFERENCES "public"."hr_notice_type"("pk_nt_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hr_announcement" ADD CONSTRAINT "hr_announcement_fk_user_id_app_user_pk_user_id_fk" FOREIGN KEY ("fk_user_id") REFERENCES "public"."app_user"("pk_user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hr_announcement" ADD CONSTRAINT "hr_announcement_fk_a_user_id_app_user_pk_user_id_fk" FOREIGN KEY ("fk_a_user_id") REFERENCES "public"."app_user"("pk_user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hr_emp_announcement" ADD CONSTRAINT "hr_emp_announcement_fk_an_id_hr_announcement_pk_an_id_fk" FOREIGN KEY ("fk_an_id") REFERENCES "public"."hr_announcement"("pk_an_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hr_emp_announcement" ADD CONSTRAINT "hr_emp_announcement_fk_ss_id_sal_structure_pk_ss_id_fk" FOREIGN KEY ("fk_ss_id") REFERENCES "public"."sal_structure"("pk_ss_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notification_log" ADD CONSTRAINT "notification_log_announcement_id_hr_announcement_pk_an_id_fk" FOREIGN KEY ("announcement_id") REFERENCES "public"."hr_announcement"("pk_an_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sync_log" ADD CONSTRAINT "sync_log_announcement_id_hr_announcement_pk_an_id_fk" FOREIGN KEY ("announcement_id") REFERENCES "public"."hr_announcement"("pk_an_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_audit_log_resource" ON "audit_log" USING btree ("resource","resource_id");--> statement-breakpoint
CREATE INDEX "idx_audit_log_user" ON "audit_log" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_file_metadata_announcement" ON "file_metadata" USING btree ("announcement_id");--> statement-breakpoint
CREATE INDEX "idx_hr_announcement_ref_no" ON "hr_announcement" USING btree ("ref_no");--> statement-breakpoint
CREATE INDEX "idx_hr_announcement_ref_date" ON "hr_announcement" USING btree ("ref_date");--> statement-breakpoint
CREATE INDEX "idx_hr_announcement_fk_nt_id" ON "hr_announcement" USING btree ("fk_nt_id");--> statement-breakpoint
CREATE INDEX "idx_hr_announcement_fk_user_id" ON "hr_announcement" USING btree ("fk_user_id");--> statement-breakpoint
CREATE INDEX "idx_hr_emp_announcement_fk_an_id" ON "hr_emp_announcement" USING btree ("fk_an_id");--> statement-breakpoint
CREATE INDEX "idx_hr_emp_announcement_fk_ss_id" ON "hr_emp_announcement" USING btree ("fk_ss_id");--> statement-breakpoint
CREATE INDEX "idx_hr_notice_type_type" ON "hr_notice_type" USING btree ("type");--> statement-breakpoint
CREATE INDEX "idx_notification_log_announcement" ON "notification_log" USING btree ("announcement_id");--> statement-breakpoint
CREATE INDEX "idx_notification_log_user" ON "notification_log" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_sync_log_announcement" ON "sync_log" USING btree ("announcement_id");--> statement-breakpoint
CREATE INDEX "idx_sal_employee_fk_set_id" ON "sal_employee" USING btree ("fk_set_id");--> statement-breakpoint
ALTER TABLE "app_user" DROP COLUMN "sync";--> statement-breakpoint
ALTER TABLE "app_user" DROP COLUMN "sys_defined";--> statement-breakpoint
ALTER TABLE "app_user_right" DROP COLUMN "sync";--> statement-breakpoint
ALTER TABLE "app_user_right" DROP COLUMN "sys_defined";--> statement-breakpoint
ALTER TABLE "app_user_report" DROP COLUMN "sync";--> statement-breakpoint
ALTER TABLE "app_user_report" DROP COLUMN "sys_defined";--> statement-breakpoint
ALTER TABLE "app_user_other" DROP COLUMN "sync";--> statement-breakpoint
ALTER TABLE "app_user_other" DROP COLUMN "sys_defined";--> statement-breakpoint
ALTER TABLE "acct_group" DROP COLUMN "sync";--> statement-breakpoint
ALTER TABLE "acct_group" DROP COLUMN "sys_defined";--> statement-breakpoint
ALTER TABLE "email_configuration" DROP COLUMN "sync";--> statement-breakpoint
ALTER TABLE "email_configuration" DROP COLUMN "sys_defined";--> statement-breakpoint
ALTER TABLE "sal_religion" DROP COLUMN "sync";--> statement-breakpoint
ALTER TABLE "sal_religion" DROP COLUMN "sys_defined";--> statement-breakpoint
ALTER TABLE "sal_castes" DROP COLUMN "sync";--> statement-breakpoint
ALTER TABLE "sal_castes" DROP COLUMN "sys_defined";--> statement-breakpoint
ALTER TABLE "sal_schedule_type" DROP COLUMN "sync";--> statement-breakpoint
ALTER TABLE "sal_schedule_type" DROP COLUMN "sys_defined";--> statement-breakpoint
ALTER TABLE "sal_skintone" DROP COLUMN "sync";--> statement-breakpoint
ALTER TABLE "sal_skintone" DROP COLUMN "sys_defined";--> statement-breakpoint
ALTER TABLE "sal_nature_of_work" DROP COLUMN "sync";--> statement-breakpoint
ALTER TABLE "sal_nature_of_work" DROP COLUMN "sys_defined";--> statement-breakpoint
ALTER TABLE "sal_it_section" DROP COLUMN "sync";--> statement-breakpoint
ALTER TABLE "sal_it_section" DROP COLUMN "sys_defined";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "fk_tit_id";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "dob";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "photo";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "fk_qual_id";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "gender";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "martial_status";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "anni";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "p_address";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "n_address";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "fk_bnk_id";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "account_no";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "pf_no";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "esic_no";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "pan_no";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "dol";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "blood_grp";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "wp";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "aadhar";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "cv_copy";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "le_copy";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "fk_m_doc_id";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "username";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "password";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "question";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "answer";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "ext";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "sync";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "sys_defined";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "date_time_stamp";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "fk_user_id";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "last_status";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "rtgs";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "s_address";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "sb";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "att_type";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "height";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "weight";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "fk_rg_id";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "fk_cs_id";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "fk_st_id";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "mark";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "experience";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "fk_r_emp_id";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "police";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "add_police";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "cont_police";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "fk_w1_emp_id";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "fk_w2_emp_id";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "personality1";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "fk_p1_des_id";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "p1_address";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "p1_contact";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "personality2";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "fk_p2_des_id";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "p2_address";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "p2_contact";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "messaging";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "fk_acct_id";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "geolocation";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "employment";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "inform_pf";--> statement-breakpoint
ALTER TABLE "sal_employee" DROP COLUMN "inform_esic";--> statement-breakpoint
ALTER TABLE "cont_department" DROP COLUMN "sync";--> statement-breakpoint
ALTER TABLE "cont_department" DROP COLUMN "sys_defined";--> statement-breakpoint
ALTER TABLE "cont_designation" DROP COLUMN "sync";--> statement-breakpoint
ALTER TABLE "cont_designation" DROP COLUMN "sys_defined";--> statement-breakpoint
ALTER TABLE "cont_qualification" DROP COLUMN "sync";--> statement-breakpoint
ALTER TABLE "cont_qualification" DROP COLUMN "sys_defined";--> statement-breakpoint
ALTER TABLE "cont_relationship" DROP COLUMN "sync";--> statement-breakpoint
ALTER TABLE "cont_relationship" DROP COLUMN "sys_defined";--> statement-breakpoint
ALTER TABLE "cont_title" DROP COLUMN "sync";--> statement-breakpoint
ALTER TABLE "cont_title" DROP COLUMN "sys_defined";--> statement-breakpoint
ALTER TABLE "cont_category" DROP COLUMN "sync";--> statement-breakpoint
ALTER TABLE "cont_category" DROP COLUMN "sys_defined";--> statement-breakpoint
ALTER TABLE "cont_moc" DROP COLUMN "sync";--> statement-breakpoint
ALTER TABLE "cont_moc" DROP COLUMN "sys_defined";--> statement-breakpoint
ALTER TABLE "cont_state" DROP COLUMN "sync";--> statement-breakpoint
ALTER TABLE "cont_state" DROP COLUMN "sys_defined";--> statement-breakpoint
ALTER TABLE "cont_city" DROP COLUMN "sync";--> statement-breakpoint
ALTER TABLE "cont_city" DROP COLUMN "sys_defined";--> statement-breakpoint
ALTER TABLE "cont_address" DROP COLUMN "sync";--> statement-breakpoint
ALTER TABLE "cont_address" DROP COLUMN "sys_defined";--> statement-breakpoint
ALTER TABLE "cont_common" DROP COLUMN "sync";--> statement-breakpoint
ALTER TABLE "cont_common" DROP COLUMN "sys_defined";--> statement-breakpoint
ALTER TABLE "cont_region" DROP COLUMN "sync";--> statement-breakpoint
ALTER TABLE "cont_region" DROP COLUMN "sys_defined";--> statement-breakpoint
ALTER TABLE "sal_leave_request" DROP COLUMN "sys_defined";--> statement-breakpoint
ALTER TABLE "sal_leave_request" DROP COLUMN "sync";--> statement-breakpoint
ALTER TABLE "sal_shift_timing" DROP COLUMN "sync";--> statement-breakpoint
ALTER TABLE "sal_shift_timing" DROP COLUMN "sys_defined";--> statement-breakpoint
ALTER TABLE "sal_loan" DROP COLUMN "sys_defined";--> statement-breakpoint
ALTER TABLE "sal_loan" DROP COLUMN "sync";--> statement-breakpoint
ALTER TABLE "sal_personal_work" DROP COLUMN "sync";--> statement-breakpoint
ALTER TABLE "sal_personal_work" DROP COLUMN "sys_defined";