-- Migration to sync sal_leave_request table schema without data loss
-- This migration converts varchar foreign keys to integer types to match the current schema

-- Step 1: Add new integer columns (temporary)
ALTER TABLE "sal_leave_request" ADD COLUMN IF NOT EXISTS "fk_emp_id_new" integer;
ALTER TABLE "sal_leave_request" ADD COLUMN IF NOT EXISTS "fk_user_id_new" integer;
ALTER TABLE "sal_leave_request" ADD COLUMN IF NOT EXISTS "fk_a_user_id_new" integer;

-- Step 2: Convert varchar data to integer and populate new columns
UPDATE "sal_leave_request" SET "fk_emp_id_new" = CAST("fk_emp_id" AS integer) WHERE "fk_emp_id" ~ '^[0-9]+$';
UPDATE "sal_leave_request" SET "fk_user_id_new" = CAST("fk_user_id" AS integer) WHERE "fk_user_id" ~ '^[0-9]+$';
UPDATE "sal_leave_request" SET "fk_a_user_id_new" = CAST("fk_a_user_id" AS integer) WHERE "fk_a_user_id" ~ '^[0-9]+$';

-- Step 3: Drop old varchar columns and rename new columns
ALTER TABLE "sal_leave_request" DROP COLUMN IF EXISTS "fk_emp_id";
ALTER TABLE "sal_leave_request" DROP COLUMN IF EXISTS "fk_user_id";
ALTER TABLE "sal_leave_request" DROP COLUMN IF EXISTS "fk_a_user_id";

ALTER TABLE "sal_leave_request" RENAME COLUMN "fk_emp_id_new" TO "fk_emp_id";
ALTER TABLE "sal_leave_request" RENAME COLUMN "fk_user_id_new" TO "fk_user_id";
ALTER TABLE "sal_leave_request" RENAME COLUMN "fk_a_user_id_new" TO "fk_a_user_id";

-- Step 4: Set NOT NULL constraints
ALTER TABLE "sal_leave_request" ALTER COLUMN "fk_emp_id" SET NOT NULL;

-- Step 5: Convert pk_lr_id from varchar to integer with sequence
-- This is more complex, requires creating a sequence and updating the primary key
ALTER TABLE "sal_leave_request" ADD COLUMN IF NOT EXISTS "pk_lr_id_new" integer GENERATED BY DEFAULT AS IDENTITY;

-- Copy existing IDs (if they are numeric)
UPDATE "sal_leave_request" SET "pk_lr_id_new" = CAST("pk_lr_id" AS integer) WHERE "pk_lr_id" ~ '^[0-9]+$';

-- Drop old primary key and column
ALTER TABLE "sal_leave_request" DROP CONSTRAINT IF EXISTS "sal_leave_request_pkey";
ALTER TABLE "sal_leave_request" DROP COLUMN IF EXISTS "pk_lr_id";

-- Rename new column and set as primary key
ALTER TABLE "sal_leave_request" RENAME COLUMN "pk_lr_id_new" TO "pk_lr_id";
ALTER TABLE "sal_leave_request" ADD PRIMARY KEY ("pk_lr_id");

-- Step 6: Recreate indexes
DROP INDEX IF EXISTS "idx_sal_lr_request_date";
DROP INDEX IF EXISTS "idx_sal_lr_fk_emp_id";
DROP INDEX IF EXISTS "idx_sal_lr_fk_user_id";
DROP INDEX IF EXISTS "idx_sal_lr_authorize";

CREATE INDEX "idx_sal_lr_request_date" ON "sal_leave_request"("request_date");
CREATE INDEX "idx_sal_lr_fk_emp_id" ON "sal_leave_request"("fk_emp_id");
CREATE INDEX "idx_sal_lr_fk_user_id" ON "sal_leave_request"("fk_user_id");
CREATE INDEX "idx_sal_lr_authorize" ON "sal_leave_request"("authorize");
