import path from 'path';
import dotenv from 'dotenv';
dotenv.config({
  path: path.resolve(process.cwd(), 'env/.env.dev'),
  override: true,
});

import { sql } from 'drizzle-orm';

async function main() {
  // Dynamically import db config so that environment variables are already loaded
  const { db } = await import('../src/config/db.config.js');

  console.log('Creating sal_office_boy and sal_office_boy_task tables...');
  try {
    await db.execute(sql`
      CREATE TABLE IF NOT EXISTS sal_office_boy (
        pk_ob_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name varchar(100) NOT NULL,
        mobile varchar(15),
        email varchar(100),
        address text,
        fk_user_id integer,
        date_time_stamp timestamp DEFAULT now() NOT NULL,
        last_status varchar(10) NOT NULL
      );
    `);
    console.log('sal_office_boy table verified/created.');

    await db.execute(sql`
      CREATE TABLE IF NOT EXISTS sal_office_boy_task (
        pk_task_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        task_name varchar(500) NOT NULL,
        reaching_date varchar(20) NOT NULL,
        reaching_time varchar(10) NOT NULL,
        status varchar(20) NOT NULL DEFAULT 'Pending',
        date_time_stamp timestamp DEFAULT now() NOT NULL,
        fk_user_id integer NOT NULL,
        fk_ob_id integer REFERENCES sal_office_boy(pk_ob_id)
      );
    `);
    console.log('sal_office_boy_task table verified/created.');
    console.log('Success!');
  } catch (error) {
    console.error('Error creating tables:', error);
    process.exit(1);
  }
}

main().then(() => process.exit(0));
