import { db } from '../../../config/db.config.js';
import { sql } from 'drizzle-orm';

async function main() {
  try {
    console.log('Creating sal_personal_work table...');
    await db.execute(sql`
      CREATE TABLE IF NOT EXISTS sal_personal_work (
        pk_pw_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        request_date TIMESTAMP NOT NULL,
        fk_emp_id integer NOT NULL,
        leaving_time TIMESTAMP NOT NULL,
        return_time TIMESTAMP NOT NULL,
        break_time INTEGER NOT NULL,
        reason VARCHAR(250) NOT NULL,
        remarks VARCHAR(250) NOT NULL,
        sync CHAR(1) NOT NULL,
        sys_defined BOOLEAN NOT NULL,
        date_timestamp TIMESTAMP NOT NULL DEFAULT NOW(),
        fk_user_id integer NOT NULL,
        last_status VARCHAR(10) NOT NULL,
        authorize BOOLEAN NOT NULL,
        a_timestamp TIMESTAMP NULL,
        fk_a_user_id integer NULL,
        CONSTRAINT fk_salpw_employee FOREIGN KEY (fk_emp_id) REFERENCES sal_employee(pk_emp_id),
        CONSTRAINT fk_salpw_user FOREIGN KEY (fk_user_id) REFERENCES app_user(pk_user_id),
        CONSTRAINT fk_salpw_auser FOREIGN KEY (fk_a_user_id) REFERENCES app_user(pk_user_id)
      );
    `);
    console.log('sal_personal_work table created successfully.');
  } catch (error) {
    console.error('Error creating table:', error);
  }
  process.exit(0);
}

main();
