// ─── sal-it-section.controller.ts ───────────────────────────────────────────
import type { Request, Response } from 'express';
import asyncHandler from 'express-async-handler';

import {
  createSalItSectionSchema,
  updateSalItSectionSchema,
  deleteSalItSectionSchema,
  listSalItSectionSchema,
} from './sal-it-section.dto.js';
import {
  listItSections,
  getItSectionById,
  createItSection,
  updateItSection,
  deleteItSection,
} from './sal-it-section.service.js';

const SAL_IT_SECTION_MODULE_NAME = 'master-salary/Income Tax Section';

// GET /sal-it-section
export const list = asyncHandler(async (req: Request, res: Response): Promise<void> => {
  const parsed = listSalItSectionSchema.parse(req.query);
  const result = await listItSections(parsed);
  if (!result.success) {
    res.build
      .withStatus(500)
      .withError('INTERNAL_ERROR', result.message)
      .withMessage('Internal Server Error')
      .fail()
      .send();
    return;
  }
  res.build
    .withStatus(200)
    .withModule(SAL_IT_SECTION_MODULE_NAME)
    .withMessage('Income Tax Section list retrieved successfully')
    .withData(result.data)
    .success()
    .send();
});

// GET /sal-it-section/:id
export const getById = asyncHandler(async (req: Request, res: Response): Promise<void> => {
  const id = parseInt(req.params.id as string, 10);
  if (isNaN(id)) {
    res.build
      .withStatus(400)
      .withError('INVALID_ID', 'ID must be a number.')
      .withMessage('Bad Request - Invalid ID')
      .fail()
      .send();
    return;
  }
  const result = await getItSectionById(id);
  if (!result.success) {
    res.build
      .withStatus(500)
      .withError('INTERNAL_ERROR', result.message)
      .withMessage('Internal Server Error')
      .fail()
      .send();
    return;
  }
  if (result.data === null) {
    res.build
      .withStatus(404)
      .withError('NOT_FOUND', 'Record not found.')
      .withMessage('Record not found')
      .fail()
      .send();
    return;
  }
  res.build
    .withStatus(200)
    .withModule(SAL_IT_SECTION_MODULE_NAME)
    .withMessage('Income Tax Section record retrieved successfully')
    .withData(result.data)
    .success()
    .send();
});

// POST /sal-it-section
export const create = asyncHandler(async (req: Request, res: Response): Promise<void> => {
  const parsed = createSalItSectionSchema.parse(req.body);
  const result = await createItSection(parsed);
  if (!result.success) {
    res.build
      .withStatus(409)
      .withError('CONFLICT', result.message)
      .withMessage('Conflict - Resource already exists')
      .fail()
      .send();
    return;
  }
  res.build
    .withStatus(201)
    .withModule(SAL_IT_SECTION_MODULE_NAME)
    .withMessage('Income Tax Section created successfully')
    .withData(result.data)
    .success()
    .send();
});

// PUT /sal-it-section/:id
export const update = asyncHandler(async (req: Request, res: Response): Promise<void> => {
  const id = parseInt(req.params.id as string, 10);
  if (isNaN(id)) {
    res.build
      .withStatus(400)
      .withError('INVALID_ID', 'ID must be a number.')
      .withMessage('Bad Request - Invalid ID')
      .fail()
      .send();
    return;
  }
  const parsed = updateSalItSectionSchema.parse({
    ...req.body,
    pk_sec_id: id,
  });
  const result = await updateItSection(parsed);
  if (!result.success) {
    const status = result.message === 'Record not found.' ? 404 : 409;
    const msg = status === 404 ? 'Record not found' : 'Conflict - Resource already exists';
    res.build
      .withStatus(status)
      .withError('UPDATE_ERROR', result.message)
      .withMessage(msg)
      .fail()
      .send();
    return;
  }
  res.build
    .withStatus(200)
    .withModule(SAL_IT_SECTION_MODULE_NAME)
    .withMessage('Income Tax Section updated successfully')
    .withData(result.data)
    .success()
    .send();
});

// DELETE /sal-it-section/:id
export const remove = asyncHandler(async (req: Request, res: Response): Promise<void> => {
  const id = parseInt(req.params.id as string, 10);
  if (isNaN(id)) {
    res.build
      .withStatus(400)
      .withError('INVALID_ID', 'ID must be a number.')
      .withMessage('Bad Request - Invalid ID')
      .fail()
      .send();
    return;
  }
  const parsed = deleteSalItSectionSchema.parse({ pk_sec_id: id });
  const result = await deleteItSection(parsed);
  if (!result.success) {
    const status =
      result.message?.includes('related to other data') ||
      result.message?.includes('generated by application')
        ? 409
        : result.message === 'Record not found.'
          ? 404
          : 500;
    const msg =
      status === 404
        ? 'Record not found'
        : status === 409
          ? 'Conflict - Deletion constraint check failed'
          : 'Internal Server Error';
    res.build
      .withStatus(status)
      .withError('DELETE_ERROR', result.message)
      .withMessage(msg)
      .fail()
      .send();
    return;
  }
  res.build
    .withStatus(200)
    .withModule(SAL_IT_SECTION_MODULE_NAME)
    .withMessage('Income Tax Section deleted successfully')
    .withData(result.data)
    .success()
    .send();
});
